table '0  MEASURES'
	lineageTag: feb1270c-eaa2-47d5-9460-24fa8480ebb7

	measure UniqueCustomers_Q =
			
			VAR k = SELECTEDVALUE( DIM_MONTH[QuarterKey] )
			RETURN
			IF (
			    NOT ISBLANK ( k ),
			    CALCULATE (
			        DISTINCTCOUNT ( FACT_CLEAN[CustomerNK] ),
			        KEEPFILTERS ( DIM_MONTH[QuarterKey] = k )
			    )
			)
		formatString: 0
		lineageTag: 4b23997b-fcfd-4587-a82e-5bece21a8485

		changedProperty = IsHidden

	measure UniqueCustomers_Cum =
			
			CALCULATE(
			    DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			    FILTER(
			        ALLSELECTED('month_map'),
			        'month_map'[YearQuarter] <= MAX('month_map'[YearQuarter])
			    )
			)
		formatString: 0
		lineageTag: eee00599-9797-4b17-a128-daf851c18413

		changedProperty = IsHidden

	measure Customers_All = ```
			
			    DISTINCTCOUNT ( DIM_CUSTOMER[CustomerNK] )
			```
		formatString: 0
		lineageTag: 000bd9fc-2434-4bf1-921f-8f523287e717

		changedProperty = IsHidden

	measure AvgSales_Q =
			AVERAGEX(
			    VALUES(DIM_MONTH[YearQuarter]),
			    CALCULATE(SUM(fact_clean[ResExt]))
			)
		lineageTag: b0cfb12b-886b-443c-8373-bc945a0a72e8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure StdDevSales_Q =
			STDEVX.P(
			    VALUES(DIM_MONTH[YearQuarter]),
			    CALCULATE(SUM(fact_clean[ResExt]))
			)
		lineageTag: 028826cc-33f3-4e5a-ba29-fc84b06ae1aa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_CV = DIVIDE([StdDevSales_Q], [AvgSales_Q], BLANK())
		lineageTag: 28122849-c902-4a45-99f9-cb6ef0ca2615

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_CV_Avg_Visible =
			
			AVERAGEX(
			    VALUES('DIM_PRODUCT'[ProductLine]),   -- 依當前篩選後的產品線集合
			    [Sales_CV]                            -- 你圖上用的 CV 量值
			)
		lineageTag: 1f4d249f-e93f-49ac-9183-c019d0684e75

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AvgSales_Q_Avg_Visible =
			
			AVERAGEX(VALUES('DIM_PRODUCT'[ProductLine]), [AvgSales_Q])
		lineageTag: 2f326236-34e1-4091-a2f4-32728d61e006

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CAGR_Sales =
			
			VAR SelMonths =
			    ALLSELECTED ( DIM_MONTH[MonthEnd] )                   -- 目前切片後的月份集合（可能是全域）
			VAR StartMonth =
			    MINX (
			        FILTER ( SelMonths, NOT ISBLANK ( CALCULATE ( [Sales] ) ) ),
			        DIM_MONTH[MonthEnd]
			    )                                                     -- 被選期間內「第一個有銷售」的月份
			VAR EndMonth   =
			    MAXX (
			        FILTER ( SelMonths, NOT ISBLANK ( CALCULATE ( [Sales] ) ) ),
			        DIM_MONTH[MonthEnd]
			    )                                                     -- 被選期間內「最後一個有銷售」的月份
			VAR StartVal   = CALCULATE ( [Sales], DIM_MONTH[MonthEnd] = StartMonth )
			VAR EndVal     = CALCULATE ( [Sales], DIM_MONTH[MonthEnd] = EndMonth )
			VAR NumMonths  = DATEDIFF ( StartMonth, EndMonth, MONTH )
			VAR NumYears   = DIVIDE ( NumMonths, 12 )
			RETURN
			IF (
			    NOT ISBLANK ( StartMonth ) && NOT ISBLANK ( EndMonth )
			        && NumYears > 0 && StartVal > 0 && EndVal > 0,
			    POWER ( DIVIDE ( EndVal, StartVal ), 1 / NumYears ) - 1,
			    BLANK ()
			)
		lineageTag: b19f5da6-a3ac-47ef-a795-8821f57ad6bf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales =
			
			SUM ( fact_clean[ResExt] )
		lineageTag: bbe2f3b4-ae99-4997-901a-ef400f63de09

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure YoY_Sales_Growth =
			
			VAR CurrentSales =
			    [Sales]
			VAR LastYearSales =
			    CALCULATE (
			        [Sales],
			        DATEADD ( DIM_MONTH[MonthEnd], -1, YEAR )
			    )
			RETURN
			    DIVIDE ( CurrentSales - LastYearSales, LastYearSales )
		lineageTag: 1511f99c-815e-444a-860f-2aece9a40bd7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CAGR_UniqueCustomers =
			
			VAR StartDate =
			    CALCULATE ( MIN ( DIM_MONTH[MonthEnd] ), ALLSELECTED ( DIM_MONTH ) )
			VAR EndDate   =
			    CALCULATE ( MAX ( DIM_MONTH[MonthEnd] ), ALLSELECTED ( DIM_MONTH ) )
			VAR StartVal  =
			    CALCULATE ( [UniqueCustomers_Cum], KEEPFILTERS ( DIM_MONTH[MonthEnd] = StartDate ) )
			VAR EndVal    =
			    CALCULATE ( [UniqueCustomers_Cum], KEEPFILTERS ( DIM_MONTH[MonthEnd] = EndDate ) )
			VAR NumMonths =
			    DATEDIFF ( StartDate, EndDate, MONTH )
			VAR NumYears  =
			    DIVIDE ( NumMonths, 12 )
			RETURN
			IF (
			    NumYears > 0 && StartVal > 0 && EndVal > 0,
			    ( EndVal / StartVal ) ^ ( 1 / NumYears ) - 1,
			    BLANK ()
			)
		lineageTag: c202167a-7c31-41a0-a692-75c641bdca0d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales (True)' =
			
			SUM ( 'customer_monthlyrfm'[NetSalesM] )
		lineageTag: 51d4fab1-7515-42b8-ad35-ab994df74275

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AnnualSales_BySegment =
			
			SUM ( 'customer_monthlyrfm'[AnnualValue] )
		lineageTag: a335ff32-6d6d-499f-b7af-6412da9c83d0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UniqueCustomers_Month =
			
			DISTINCTCOUNT( 'customer_monthlyrfm'[CustomerNK] )
		formatString: 0
		lineageTag: 5ae70110-36a8-4ed7-8578-5a32a9e8e471

		changedProperty = IsHidden

	measure CAGR_UniqueCustomers_country =
			
			VAR StartDate =
			    MINX( ALLSELECTED( DIM_MONTH[MonthEnd] ), DIM_MONTH[MonthEnd] )
			VAR EndDate   =
			    MAXX( ALLSELECTED( DIM_MONTH[MonthEnd] ), DIM_MONTH[MonthEnd] )
			VAR StartVal  =
			    CALCULATE( [UniqueCustomers_Month], DIM_MONTH[MonthEnd] = StartDate )
			VAR EndVal    =
			    CALCULATE( [UniqueCustomers_Month], DIM_MONTH[MonthEnd] = EndDate )
			VAR NumMonths = DATEDIFF( StartDate, EndDate, MONTH )
			VAR NumYears  = DIVIDE( NumMonths, 12 )
			RETURN
			IF(
			    NumYears > 0 && StartVal > 0 && EndVal > 0,
			    ( EndVal / StartVal ) ^ ( 1 / NumYears ) - 1
			)
		lineageTag: 7a61ac3e-66a4-43bc-ad92-0f2736d93fe0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CAGR_UniqueCustomers2 =
			
			VAR MonthsVisible =
			    FILTER ( VALUES ( DIM_MONTH[MonthEnd] ), NOT ISBLANK ( [UniqueCustomers_Month] ) )
			VAR StartDate = MINX ( MonthsVisible, DIM_MONTH[MonthEnd] )
			VAR EndDate   = MAXX ( MonthsVisible, DIM_MONTH[MonthEnd] )
			VAR StartVal  = CALCULATE ( [UniqueCustomers_Month], DIM_MONTH[MonthEnd] = StartDate )
			VAR EndVal    = CALCULATE ( [UniqueCustomers_Month], DIM_MONTH[MonthEnd] = EndDate )
			VAR NumMonths = DATEDIFF ( StartDate, EndDate, MONTH )  -- ← 改這行
			RETURN
			IF (
			    NumMonths >= 1 && StartVal > 0 && EndVal > 0,
			    POWER ( DIVIDE ( EndVal, StartVal ), 12 / NumMonths ) - 1
			)
		lineageTag: 8da95ad1-527f-4213-968b-c456244df414

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UniqueCustomers_Qtr =
			
			VAR DatesInScope =
			    VALUES ( DIM_MONTH[MonthEnd] )      -- 目前範圍（通常是一季內的各月份）
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    TREATAS ( DatesInScope, 'customer_monthlyrfm'[MonthEnd] )
			)
		formatString: 0
		lineageTag: cc42cae3-da9c-4513-83d1-242109b6666a

		changedProperty = IsHidden

	measure UniqueCustomers_PrevQtr =
			
			VAR PrevQtrDates =
			    PREVIOUSQUARTER ( DIM_MONTH[MonthEnd] )   -- 取前一季的日期集合
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    TREATAS ( PrevQtrDates, 'customer_monthlyrfm'[MonthEnd] )
			)
		formatString: 0
		lineageTag: 9efe572c-7991-4509-800c-36a9df5a5b25

		changedProperty = IsHidden

	measure UniqueCustomers_QoQ_Delta =
			
			VAR Qs =
			    CALCULATETABLE (
			        VALUES ( DIM_MONTH[QuarterKey] ),
			        ALLSELECTED ( DIM_MONTH[QuarterKey] )     -- 只看可見的季，保留其它切片器
			    )
			VAR CurrQ =
			    MAXX ( Qs, DIM_MONTH[QuarterKey] )
			VAR PrevQ =
			    MAXX ( FILTER ( Qs, DIM_MONTH[QuarterKey] < CurrQ ), DIM_MONTH[QuarterKey] )
			VAR CurrVal =
			    CALCULATE ( [UniqueCustomers], KEEPFILTERS ( DIM_MONTH[QuarterKey] = CurrQ ) )
			VAR PrevVal =
			    CALCULATE ( [UniqueCustomers], KEEPFILTERS ( DIM_MONTH[QuarterKey] = PrevQ ) )
			RETURN
			IF ( NOT ISBLANK ( PrevVal ), CurrVal - PrevVal )
		formatString: 0
		lineageTag: 55074288-8a2b-45b8-ab9b-f8591abdd40b

		changedProperty = IsHidden

	measure UniqueCustomers_QoQ_% =
			
			VAR Qs =
			    CALCULATETABLE (
			        VALUES ( DIM_MONTH[QuarterKey] ),
			        ALLSELECTED ( DIM_MONTH[QuarterKey] )
			    )
			VAR CurrQ =
			    MAXX ( Qs, DIM_MONTH[QuarterKey] )
			VAR PrevQ =
			    MAXX ( FILTER ( Qs, DIM_MONTH[QuarterKey] < CurrQ ), DIM_MONTH[QuarterKey] )
			VAR CurrVal =
			    CALCULATE ( [UniqueCustomers], KEEPFILTERS ( DIM_MONTH[QuarterKey] = CurrQ ) )
			VAR PrevVal =
			    CALCULATE ( [UniqueCustomers], KEEPFILTERS ( DIM_MONTH[QuarterKey] = PrevQ ) )
			RETURN
			IF ( NOT ( ISBLANK ( PrevVal ) || PrevVal = 0 ), DIVIDE ( CurrVal - PrevVal, PrevVal ) )
		lineageTag: f4e34552-2558-4cb1-858b-18e6af0aa8f7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UniqueCustomers =
			
			DISTINCTCOUNT ( customer_monthlyrfm[CustomerNK] )
		formatString: 0
		lineageTag: 51f54a30-cb85-43aa-bca9-230a072e459c

		changedProperty = IsHidden

	measure Sales_Q_Tier =
			
			VAR CurrQ = SELECTEDVALUE( DIM_MONTH[QuarterKey] )
			VAR MonthsInQ =
			    CALCULATETABLE(
			        VALUES( DIM_MONTH[MonthEnd] ),
			        KEEPFILTERS( DIM_MONTH[QuarterKey] = CurrQ )
			    )
			RETURN
			CALCULATE(
			    SUM( customer_monthlyrfm[NetSalesM] ),   -- 或用 MonthlySales，看你模型欄位
			    TREATAS( MonthsInQ, customer_monthlyrfm[MonthEnd] )
			)
		lineageTag: 3a939534-96bb-4000-8235-110fdefeef9a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_QoQ_Delta_Tier = ```
			
			VAR Qs =
			    CALCULATETABLE( VALUES( DIM_MONTH[QuarterKey] ), ALLSELECTED( DIM_MONTH ) )
			VAR CurrQ = MAXX( Qs, DIM_MONTH[QuarterKey] )
			VAR PrevQ = MAXX( FILTER( Qs, DIM_MONTH[QuarterKey] < CurrQ ), DIM_MONTH[QuarterKey] )
			VAR CurrVal = CALCULATE( [Sales_Q_Tier], TREATAS( { CurrQ }, DIM_MONTH[QuarterKey] ) )
			VAR PrevVal = CALCULATE( [Sales_Q_Tier], TREATAS( { PrevQ }, DIM_MONTH[QuarterKey] ) )
			RETURN IF( NOT ISBLANK( PrevVal ), CurrVal - PrevVal )
			
			```
		lineageTag: d1846faa-25a2-4bc4-b6cc-f0bdce209567

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_QoQ_%_Tier =
			
			VAR Qs =
			    CALCULATETABLE( VALUES( DIM_MONTH[QuarterKey] ), ALLSELECTED( DIM_MONTH ) )
			VAR CurrQ = MAXX( Qs, DIM_MONTH[QuarterKey] )
			VAR PrevQ = MAXX( FILTER( Qs, DIM_MONTH[QuarterKey] < CurrQ ), DIM_MONTH[QuarterKey] )
			VAR CurrVal = CALCULATE( [Sales_Q_Tier], TREATAS( { CurrQ }, DIM_MONTH[QuarterKey] ) )
			VAR PrevVal = CALCULATE( [Sales_Q_Tier], TREATAS( { PrevQ }, DIM_MONTH[QuarterKey] ) )
			RETURN IF( NOT ISBLANK( PrevVal ) && PrevVal <> 0, DIVIDE( CurrVal - PrevVal, PrevVal ) )
		lineageTag: 190f00da-3418-4375-82df-9b760a53be57

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Count (Rolling12_Label)' =
			
			CALCULATE (
			    DISTINCTCOUNT ( sales_m_pdl[ProductLine] ),
			    sales_m_pdl[Sales] > 0
			)
		formatString: 0
		lineageTag: f4cc2795-201f-4ffc-886f-7e55dfcb5f0b

		changedProperty = IsHidden

	measure 'PDL Count (per customer)' =
			
			VAR Cust =
			    COALESCE(
			        SELECTEDVALUE ( 'sales_m_pdl'[CustomerNK] ),
			        SELECTEDVALUE ( customer_monthlyrfm[CustomerNK] ),
			        SELECTEDVALUE ( DIM_CUSTOMER[CustomerNK] )
			    )
			
			-- 兩張表的月份並集（已受目前報表篩選影響）
			VAR Months =
			    DISTINCT (
			        UNION (
			            CALCULATETABLE (
			                SELECTCOLUMNS ( customer_monthlyrfm, "MonthEnd", customer_monthlyrfm[MonthEnd] )
			            ),
			            CALCULATETABLE (
			                SELECTCOLUMNS ( 'sales_m_pdl', "MonthEnd", 'sales_m_pdl'[MonthEnd] )
			            )
			        )
			    )
			
			VAR CustPLs =
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[ProductLine] ),               -- 要計的 PDL
			        KEEPFILTERS ( 'sales_m_pdl'[CustomerNK] = Cust ),    -- 此客戶
			        TREATAS ( Months, 'sales_m_pdl'[MonthEnd] ),         -- 把月份上下文套到 sales_m_pdl
			        'sales_m_pdl'[Sales] <> 0                            -- 排除 0 銷售
			    )
			RETURN
			    IF ( NOT ISBLANK ( Cust ), COUNTROWS ( CustPLs ) )
		formatString: 0
		lineageTag: b0e893ac-dfac-4c3d-b708-88e4ff2a8d80

		changedProperty = IsHidden

	measure 'Avg PDL per Customer (since first, seg-aware • vectorized)' =
			
			VAR EndMonth =
			    MAX ( 'dim_month'[MonthEnd] )                     -- 建議 MonthEnd 單選；若未選就取最大月
			VAR CustSet =
			    CALCULATETABLE (                                  -- 這個月、目前分群下的「客戶名單」
			        VALUES ( customer_monthlyrfm[CustomerNK] ),
			        customer_monthlyrfm[MonthEnd] = EndMonth,
			        KEEPFILTERS ( VALUES ( customer_monthlyrfm[CustomerSegment] ) )
			    )
			
			-- 1) 先把「客戶 × PDL」跨所有時間去重（只保留有買過）
			VAR CustPDL_PairsAllTime =
			    CALCULATETABLE (
			        SUMMARIZE (
			            'sales_m_pdl',
			            'sales_m_pdl'[CustomerNK],
			            'sales_m_pdl'[ProductLine]
			        ),
			        ALL ( 'dim_month' ),                           -- 忽略時間 ＝ 從首購以來
			        'sales_m_pdl'[Sales] <> 0,                     -- 有交易才算
			        TREATAS ( CustSet, 'sales_m_pdl'[CustomerNK] ) -- 只留當月該分群的客戶
			    )
			
			-- 2) 以客戶分組，數每位客戶的不重複 PDL 數
			VAR PerCustCounts =
			    GROUPBY (
			        CustPDL_PairsAllTime,
			        'sales_m_pdl'[CustomerNK],
			        "PDLCount", COUNTX ( CURRENTGROUP (), 'sales_m_pdl'[ProductLine] )
			        -- 也可寫成 COUNTX(CURRENTGROUP(), 1)
			    )
			
			RETURN
			    AVERAGEX ( PerCustCounts, [PDLCount] )
		lineageTag: 717a4fbc-d110-4a31-b6eb-16a7b803a305

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Count (since first, per customer)' =
			
			VAR CustNK =
			    COALESCE (
			        SELECTEDVALUE ( 'sales_m_pdl'[CustomerNK] ),
			        SELECTEDVALUE ( customer_monthlyrfm[CustomerNK] )
			    )
			RETURN
			IF (
			    NOT ISBLANK ( CustNK ),
			    CALCULATE (
			        DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ),
			        -- 把所有「時間」來源的濾器清掉
			        ALL ( 'dim_month' ),
			        REMOVEFILTERS ( customer_monthlyrfm[MonthEnd] ),
			        REMOVEFILTERS ( customer_monthlyrfm[Rolling12M_Label] ),
			        -- 只保留指定客戶（布林條件比 TREATAS 更快）
			        'sales_m_pdl'[CustomerNK] = CustNK,
			        'sales_m_pdl'[Sales] <> 0
			    )
			)
		formatString: 0
		lineageTag: f65c6ae6-5989-4f2b-898c-d43e9cc3499d

		changedProperty = IsHidden

	measure 'PDL Count (last 24M, per customer)' =
			
			VAR CustNK =
			    COALESCE (
			        SELECTEDVALUE ( 'sales_m_pdl'[CustomerNK] ),
			        SELECTEDVALUE ( customer_monthlyrfm[CustomerNK] )
			    )
			VAR EndMonth =
			    MAX ( 'dim_month'[MonthEnd] )   -- 視覺或切片器選到的結束月份
			VAR Win24M =
			    DATESINPERIOD ( 'dim_month'[MonthEnd], EndMonth, -24, MONTH )
			RETURN
			IF (
			    NOT ISBLANK ( CustNK ),
			    CALCULATE (
			        DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ),
			        -- 先清掉所有其它時間來源的濾器
			        REMOVEFILTERS ( 'dim_month' ),
			        REMOVEFILTERS ( customer_monthlyrfm[MonthEnd] ),
			        REMOVEFILTERS ( customer_monthlyrfm[Rolling12M_Label] ),
			        -- 套用「前 24 個月」視窗
			        KEEPFILTERS ( Win24M ),
			        -- 只保留該客戶 + 有購買的紀錄
			        'sales_m_pdl'[CustomerNK] = CustNK,
			        'sales_m_pdl'[Sales] <> 0
			    )
			)
		formatString: 0
		lineageTag: 06eeba80-3b17-44e2-9005-7d00bd0e0ea6

		changedProperty = IsHidden

	measure Customers_Row =
			
			VAR EndMonth =
			    MAX ( 'dim_month'[MonthEnd] )   -- 多選時會用到最大那一個；若要強制單選可改 SELECTEDVALUE
			VAR RowPL = SELECTEDVALUE ( 'sales_m_pdl'[ProductLine] )
			VAR ToDate =
			    FILTER (
			        ALL ( 'dim_month'[MonthEnd] ),        -- 清掉原有日期濾器
			        'dim_month'[MonthEnd] <= EndMonth     -- 到 EndMonth 為止
			    )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'sales_m_pdl'[CustomerNK] ),
			    ToDate,
			    'sales_m_pdl'[ProductLine] = RowPL,
			    'sales_m_pdl'[Sales] <> 0
			)
		formatString: 0
		lineageTag: afbda0db-a2d7-439d-9f9e-bd76fad698e5

		changedProperty = IsHidden

	measure Customers_Both =
			
			VAR EndMonth =
			    MAX ( 'dim_month'[MonthEnd] )   -- 單選或取最大值
			VAR RowPL = SELECTEDVALUE ( 'sales_m_pdl'[ProductLine] )
			VAR ColPL = SELECTEDVALUE ( ProductLine_Col[ProductLine] )
			
			VAR ToDate =
			    FILTER (
			        ALL ( 'dim_month'[MonthEnd] ),
			        'dim_month'[MonthEnd] <= EndMonth
			    )
			
			VAR CustRow =
			    CALCULATETABLE (
			        DISTINCT ( 'sales_m_pdl'[CustomerNK] ),
			        ToDate,
			        'sales_m_pdl'[ProductLine] = RowPL,
			        'sales_m_pdl'[Sales] <> 0
			    )
			VAR CustCol =
			    CALCULATETABLE (
			        DISTINCT ( 'sales_m_pdl'[CustomerNK] ),
			        ToDate,
			        'sales_m_pdl'[ProductLine] = ColPL,
			        'sales_m_pdl'[Sales] <> 0
			    )
			RETURN
			COUNTROWS ( INTERSECT ( CustRow, CustCol ) )
		formatString: 0
		lineageTag: e8756487-1df5-42f6-a842-c7bf26efddc8

		changedProperty = IsHidden

	measure 'Cross % of Row' =
			
			VAR RowPL = SELECTEDVALUE ( 'sales_m_pdl'[ProductLine] )
			VAR ColPL = SELECTEDVALUE ( ProductLine_Col[ProductLine] )
			VAR pct   = DIVIDE ( [Customers_Both], [Customers_Row] )
			RETURN IF ( RowPL = ColPL, BLANK(), pct )
		lineageTag: fa4ecf0d-1359-4deb-8a0e-7973b99e38fc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Adj Items Count (to date, per customer)' =
			
			VAR CustNK =
			    COALESCE (
			        SELECTEDVALUE ( 'sales_m_pdl'[CustomerNK] ),
			        SELECTEDVALUE ( customer_monthlyrfm[CustomerNK] )
			    )
			VAR EndMonth =
			    MAX ( 'dim_month'[MonthEnd] )
			VAR ToDate =
			    FILTER ( ALL ( 'dim_month'[MonthEnd] ), 'dim_month'[MonthEnd] <= EndMonth )
			RETURN
			IF (
			    NOT ISBLANK ( CustNK ),
			    CALCULATE (
			        DISTINCTCOUNT ( fact_clean[AdjPtNo] ),
			        ToDate,
			        fact_clean[CustomerNK] = CustNK,
			        fact_clean[ResExt] <> 0     -- 這裡用 fact_clean 的金額欄位替代 Sales 判斷
			    )
			)
		formatString: 0
		lineageTag: f181eb79-cd1d-4558-9499-6e29132e86ac

		changedProperty = IsHidden

	measure 'Avg Adj Items per Customer (to date, seg-aware · vectorized)' =
			
			VAR EndMonth =
			    MAX ( 'dim_month'[MonthEnd] )              -- 建議 MonthEnd 單選；未選則取最大月
			
			-- 這個月、目前視覺條件(Geo/Dist/Seg)下的「客戶名單」
			VAR CustSet =
			    CALCULATETABLE (
			        VALUES ( customer_monthlyrfm[CustomerNK] ),
			        customer_monthlyrfm[MonthEnd] = EndMonth,
			        KEEPFILTERS ( VALUES ( customer_monthlyrfm[CustomerSegment] ) ),
			        KEEPFILTERS ( VALUES ( customer_monthlyrfm[GeoGroup] ) ),
			        KEEPFILTERS ( VALUES ( customer_monthlyrfm[DistName] ) )
			    )
			
			-- 「到 EndMonth 為止」的月份清單（忽略任何現有月份切片器）
			VAR ToDateMonths =
			    FILTER ( ALL ( 'dim_month'[MonthEnd] ), 'dim_month'[MonthEnd] <= EndMonth )
			
			-- 1) 先把「客戶×AdjPtNo」跨時間去重，只留有交易
			VAR CustItemPairs_ToDate =
			    CALCULATETABLE (
			        SUMMARIZE (
			            fact_clean,
			            fact_clean[CustomerNK],
			            fact_clean[AdjPtNo]
			        ),
			        ToDateMonths,
			        fact_clean[ResExt] <> 0,                        -- 有買才算
			        TREATAS ( CustSet, fact_clean[CustomerNK] )     -- 只留當月該分群/區域/通路的客戶
			    )
			
			-- 2) 以客戶分組，數每位客戶的不重複 AdjPtNo 數
			VAR PerCustCounts =
			    GROUPBY (
			        CustItemPairs_ToDate,
			        fact_clean[CustomerNK],
			        "ItemCount", COUNTX ( CURRENTGROUP (), 1 )
			    )
			
			RETURN
			    AVERAGEX ( PerCustCounts, [ItemCount] )
		lineageTag: 61c15e8a-daee-411f-9fb6-1202bd139357

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GM (Rolling12M)' = SUM ( FACT_SALES_MONTH[ResExt] )
		lineageTag: e453faf2-1c0e-470e-8522-095012f7be74

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active Customers (Rolling12M)' =
			
			CALCULATE (
			    DISTINCTCOUNT ( FACT_SALES_MONTH[CustomerNK] ),
			    FACT_SALES_MONTH[MonthlySales] > 0
			)
		formatString: 0
		lineageTag: 64c2683d-b7ab-4a37-8bea-32bdf18da969

		changedProperty = IsHidden

	measure 'Active Items (R12 by Label • flexible)' =
			
			VAR EndMonth = MAX ( 'dim_month'[MonthEnd] )
			
			-- 解析圖例：Current = 0；Current-1 = 1；...
			VAR Label =
			    SELECTEDVALUE ( R12Label[Rolling12M_Label], "Current" )
			VAR BackK =
			    IF ( Label = "Current", 0, VALUE ( SUBSTITUTE ( Label, "Current-", "" ) ) )
			
			-- 依 BackK 回推對應的 12M 起訖
			VAR StartDate = EOMONTH ( EndMonth, -11 - 12 * BackK )
			VAR StopDate  = EOMONTH ( EndMonth,       - 12 * BackK )
			
			-- 用 dim_month 產出這個視窗的月份集合（避免 fact 端空白類別）
			VAR MonthsInScope =
			    FILTER (
			        ALL ( 'dim_month'[MonthEnd] ),
			        'dim_month'[MonthEnd] >= StartDate
			            && 'dim_month'[MonthEnd] <= StopDate
			    )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( FACT_SALES_MONTH[AdjPtNo] ), -- 交易品項（不重複）
			    MonthsInScope,                                 -- 以 dim_month 控窗
			    FACT_SALES_MONTH[ResExt] <> 0                -- 有交易才算
			)
		formatString: 0
		lineageTag: e4ee2fe7-e44e-46cc-8165-379959964aee

		changedProperty = IsHidden

	measure 'Median AnnualValue by Segment' =
			
			MEDIANX (
			    VALUES ( customer_monthlyrfm[CustomerNK] ),
			    CALCULATE ( MAX ( customer_monthlyrfm[AnnualValue] ) )
			)
		lineageTag: 7e901707-f1b9-429a-b438-19db73fb975f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IsRSJP =
			
			IF (
			    CALCULATE (
			        COUNTROWS ( PlatformListing ),
			        PlatformListing[Platform] = "RSJP",
			        PlatformListing[OnShelf] = "Y"
			    ) > 0,
			    1, 0
			)
		formatString: 0
		lineageTag: f344aca7-0a6d-4cdc-94b0-08726adb2dce

		changedProperty = IsHidden

	measure RSJP_Flag =
			
			IF( COUNTROWS( RELATEDTABLE('PlatformListing') ) > 0,
			    "RSJP上架", "未上架"
			)
		lineageTag: e9225f98-1e39-45b0-9f2e-2c63efb989e1

		changedProperty = IsHidden

	measure 'New Customers (First ≥ 2024)' =
			
			VAR _cut = DATE ( 2024, 1, 1 )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    -- 只移除 MonthEnd 的時間篩選
			    ALL ( 'customer_monthlyrfm'[MonthEnd] ),
			    -- 用 FILTER(ALL()) 明確建立要套條件的表，並把時間截掉避免 Date/DateTime 比較問題
			    FILTER (
			        ALL ( 'customer_monthlyrfm' ),
			        NOT ISBLANK ( 'customer_monthlyrfm'[FirstPurchaseMonth] )
			            && TRUNC ( 'customer_monthlyrfm'[FirstPurchaseMonth] ) >= _cut
			    )
			)
		formatString: 0
		lineageTag: 88fd3987-5300-4163-b596-16396b2a097a

		changedProperty = IsHidden

	measure 'New Customers Became Core within 12M' =
			
			VAR _cut = DATE ( 2024, 1, 1 )
			VAR _BaseCustomers =
			    CALCULATETABLE (
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] ),
			        ALL ( 'customer_monthlyrfm'[MonthEnd] ),
			        FILTER (
			            ALL ( 'customer_monthlyrfm' ),
			            NOT ISBLANK ( 'customer_monthlyrfm'[FirstPurchaseMonth] )
			                && TRUNC ( 'customer_monthlyrfm'[FirstPurchaseMonth] ) >= _cut
			        )
			    )
			RETURN
			COUNTROWS (
			    FILTER (
			        _BaseCustomers,
			        VAR cust =
			            'customer_monthlyrfm'[CustomerNK]
			        VAR fp =
			            CALCULATE (
			                MIN ( 'customer_monthlyrfm'[FirstPurchaseMonth] ),
			                ALL ( 'customer_monthlyrfm'[MonthEnd] ),
			                'customer_monthlyrfm'[CustomerNK] = cust
			            )
			        RETURN
			            CALCULATE (
			                COUNTROWS ( 'customer_monthlyrfm' ),
			                ALL ( 'customer_monthlyrfm'[MonthEnd] ),
			                'customer_monthlyrfm'[CustomerNK] = cust,
			                'customer_monthlyrfm'[CustomerSegment] = "Core",
			                'customer_monthlyrfm'[MonthEnd] >= fp,
			                'customer_monthlyrfm'[MonthEnd] <  EDATE ( fp, 12 )
			            ) > 0
			    )
			)
		formatString: 0
		lineageTag: 8f82af77-ece3-46ce-b282-e700f146d13e

		changedProperty = IsHidden

	measure 'New Core % (first purchase ≥ 2024, within 12M)' =
			
			DIVIDE (
			    [New Customers Became Core within 12M],
			    [New Customers (First ≥ 2024)]
			)
		lineageTag: 40b3591a-184b-4eb1-891b-71cc60f8bece

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'R12M Annual Purchase' =
			
			VAR _anchor = [MonthEnd_Selected]
			RETURN
			CALCULATE (
			    [GM (Rolling12M)],
			    DATESINPERIOD ( FACT_SALES_MONTH[MonthEnd], _anchor, -12, MONTH )
			)
		lineageTag: 73b33a03-a41a-4a04-ab7f-be332ad1708b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NewCustomer_Current12M =
			
			VAR _maxMonth =
			    CALCULATE(
			        MAX(customer_monthlyrfm[MonthEnd]),
			        REMOVEFILTERS(customer_monthlyrfm)
			    )
			RETURN
			CALCULATE(
			    DISTINCTCOUNT(customer_monthlyrfm[CustomerNK]),
			    customer_monthlyrfm[IsNew] = TRUE(),
			    DATESINPERIOD(customer_monthlyrfm[MonthEnd], _maxMonth, -12, MONTH)
			)
		formatString: 0
		lineageTag: 480d7874-0a32-40d2-8597-ea23dcc1b8d9

		changedProperty = IsHidden

	measure NewCustomer_Prior12M =
			
			VAR _maxMonth =
			    CALCULATE(
			        MAX(customer_monthlyrfm[MonthEnd]),
			        REMOVEFILTERS(customer_monthlyrfm)
			    )
			VAR _priorAnchor = EDATE(_maxMonth, -12)
			RETURN
			CALCULATE(
			    DISTINCTCOUNT(customer_monthlyrfm[CustomerNK]),
			    customer_monthlyrfm[IsNew] = TRUE(),
			    DATESINPERIOD(customer_monthlyrfm[MonthEnd], _priorAnchor, -12, MONTH)
			)
		formatString: 0
		lineageTag: ef334cb9-6df2-4387-8622-4a8b32ebd278

		changedProperty = IsHidden

	measure 'Penetration Growth (%)' =
			
			VAR _curr = [NewCustomer_Current12M]
			VAR _prev = [NewCustomer_Prior12M]
			RETURN
			IF(
			    _prev = 0,
			    BLANK(),
			    DIVIDE(_curr, _prev)
			)
		lineageTag: b32ffed8-22fb-4b35-b954-77b59616a096

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GM_12M_Total_Safe =
			
			VAR _anchor = [AnchorMonth_Robust]           -- 你通過的錨點（或用 AnchorMonth_Final）
			VAR _start  = EOMONTH ( _anchor, -11 )
			VAR _dates  = CALENDAR ( _start, _anchor )    -- 這 12 個月的虛擬日曆
			RETURN
			IF (
			    NOT ISBLANK ( _anchor ),
			    CALCULATE (
			        SUM ( FACT_SALES_MONTH[ResExt] ),
			
			        -- 只把 12 個月的日期投到 fact 的 MonthEnd
			        TREATAS ( _dates, FACT_SALES_MONTH[MonthEnd] ),
			
			        -- 逐一移除其它來源上的 MonthEnd 過濾（注意每個都分開寫）
			        REMOVEFILTERS ( dim_month ),
			        REMOVEFILTERS ( customer_monthlyrfm[MonthEnd] ),
			        REMOVEFILTERS ( customer_monthlyrfm_global[MonthEnd] ),
			        REMOVEFILTERS ( product_quadrant_month[MonthEnd] ),
			        REMOVEFILTERS ( sales_m_pdl[MonthEnd] )
			    )
			)
		lineageTag: b758ac72-75cf-473e-8817-d09076893006

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GM_12M_Repeat =
			
			VAR _maxMonth =
			    CALCULATE(
			        MAX(customer_monthlyrfm[MonthEnd]),
			        REMOVEFILTERS(customer_monthlyrfm)
			    )
			VAR _oldCustomers =
			    CALCULATETABLE(
			        VALUES(customer_monthlyrfm[CustomerNK]),
			        customer_monthlyrfm[IsNew] = FALSE(),
			        DATESINPERIOD(customer_monthlyrfm[MonthEnd], _maxMonth, -12, MONTH)
			    )
			RETURN
			CALCULATE(
			    SUM(FACT_SALES_MONTH[ResExt]),
			    DATESINPERIOD(FACT_SALES_MONTH[MonthEnd], _maxMonth, -12, MONTH),
			    TREATAS(_oldCustomers, FACT_SALES_MONTH[CustomerNK])
			)
		lineageTag: 5fd7fa68-a74d-4056-9fd1-185386dad71e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RepeatCustomer_12M =
			
			VAR _anchor = CALCULATE(MAX(customer_monthlyrfm[MonthEnd]))
			VAR _current12M =
			    CALCULATETABLE(
			        VALUES(customer_monthlyrfm[CustomerNK]),
			        DATESINPERIOD(customer_monthlyrfm[MonthEnd], _anchor, -12, MONTH)
			    )
			VAR _previous12M =
			    CALCULATETABLE(
			        VALUES(customer_monthlyrfm[CustomerNK]),
			        DATESINPERIOD(customer_monthlyrfm[MonthEnd], EDATE(_anchor, -12), -12, MONTH)
			    )
			VAR _repeatCust =
			    INTERSECT(_current12M, _previous12M)
			RETURN
			CALCULATE(
			    DIVIDE(
			        CALCULATE(
			            SUM(FACT_SALES_MONTH[ResExt]),
			            TREATAS(_repeatCust, FACT_SALES_MONTH[CustomerNK]),
			            DATESINPERIOD(FACT_SALES_MONTH[MonthEnd], _anchor, -12, MONTH)
			        ),
			        CALCULATE(
			            SUM(FACT_SALES_MONTH[ResExt]),
			            DATESINPERIOD(FACT_SALES_MONTH[MonthEnd], _anchor, -12, MONTH)
			        )
			    )
			)
		lineageTag: 4f3d1d6f-5798-457c-a813-05fcb2e478db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ValueConcentration_Top20Pct =
			
			VAR _anchor = [AnchorMonth_Safe]   -- 用剛做的安全 Anchor
			VAR _cust12m =
			    ADDCOLUMNS(
			        SUMMARIZE( FACT_SALES_MONTH, FACT_SALES_MONTH[CustomerNK] ),
			        "GM12M",
			            CALCULATE(
			                SUM( FACT_SALES_MONTH[ResExt] ),   -- ← 改這裡！你實際的金額欄位是 ResExt
			                KEEPFILTERS(
			                    DATESINPERIOD(
			                        FACT_SALES_MONTH[MonthEnd],   -- 你的月份欄位
			                        _anchor,
			                        -12,
			                        MONTH
			                    )
			                )
			            )
			    )
			VAR _custPos = FILTER( _cust12m, [GM12M] > 0 )
			VAR _totalGM = SUMX( _custPos, [GM12M] )
			VAR _n = COUNTROWS( _custPos )
			VAR _topN = MAX( 1, CEILING( _n * 0.2, 1 ) )   -- 取前 20% 客戶數，至少 1 人
			VAR _ranked =
			    ADDCOLUMNS(
			        _custPos,
			        "rk", RANKX( _custPos, [GM12M], , DESC, DENSE )
			    )
			VAR _gmTop = SUMX( FILTER( _ranked, [rk] <= _topN ), [GM12M] )
			RETURN
			    DIVIDE( _gmTop, _totalGM )
		lineageTag: 4c7d8394-c496-4e1d-b509-c6066d3a4127

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AnchorMonth_Safe =
			
			VAR sel =
			    SELECTEDVALUE ( dim_month[MonthEnd] )
			RETURN
			    COALESCE ( sel, CALCULATE ( MAX ( dim_month[MonthEnd] ), ALL ( dim_month ) ) )
		formatString: General Date
		lineageTag: ccd985d1-6494-4cff-875e-063252b8f68b

	measure AnchorMonth_Robust =
			
			VAR _sel   = SELECTEDVALUE ( dim_month[MonthEnd] )
			VAR _dimMx = CALCULATE ( MAX ( dim_month[MonthEnd] ), ALL ( dim_month ) )
			VAR _factMx = CALCULATE ( MAX ( FACT_SALES_MONTH[MonthEnd] ), ALL ( FACT_SALES_MONTH ) )
			RETURN COALESCE ( _sel, _dimMx, _factMx )
		formatString: General Date
		lineageTag: 2cee2948-531a-4369-901b-1e5705ea6f3c

	measure 'Customer Count' = DISTINCTCOUNT(FACT_SALES_MONTH[CustomerNK])
		formatString: 0
		lineageTag: 28b69d23-a370-419b-8232-7d74958a9ecd

	measure 'PDL Count TTM - Max' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartDate = EDATE(EndMonth, -11)
			VAR CustomersTTM =
			    ADDCOLUMNS (
			        CALCULATETABLE (
			            VALUES ( 'sales_m_pdl'[CustomerNK] ),
			            DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth )
			        ),
			        "PDLCount",
			            CALCULATE (
			                DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ),
			                DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth ),
			                'sales_m_pdl'[Sales] <> 0
			            )
			    )
			RETURN
			MAXX ( CustomersTTM, [PDLCount] )
		formatString: 0
		lineageTag: d39f9953-472e-45db-8753-b87b72fdd29d

	measure 'PDL Count TTM - Min' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartDate = EDATE(EndMonth, -11)
			VAR CustomersTTM =
			    ADDCOLUMNS (
			        CALCULATETABLE (
			            VALUES ( 'sales_m_pdl'[CustomerNK] ),
			            DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth )
			        ),
			        "PDLCount",
			            CALCULATE (
			                DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ),
			                DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth ),
			                'sales_m_pdl'[Sales] <> 0
			            )
			    )
			RETURN
			MINX ( CustomersTTM, [PDLCount] )
		formatString: 0
		lineageTag: 69518d2b-173b-41c1-be1b-4e1e5d32602e

	measure 'PDL Count TTM - Median' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartDate = EDATE(EndMonth, -11)
			VAR CustomersTTM =
			    ADDCOLUMNS (
			        CALCULATETABLE (
			            VALUES ( 'sales_m_pdl'[CustomerNK] ),
			            DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth )
			        ),
			        "PDLCount",
			            CALCULATE (
			                DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ),
			                DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth ),
			                'sales_m_pdl'[Sales] <> 0
			            )
			    )
			RETURN
			MEDIANX ( CustomersTTM, [PDLCount] )
		lineageTag: 4d666e21-48cb-4de6-9755-9d43c460d143

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Count TTM - StdDev (Pop)' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartDate = EDATE(EndMonth, -11)
			VAR CustomersTTM =
			    ADDCOLUMNS (
			        CALCULATETABLE (
			            VALUES ( 'sales_m_pdl'[CustomerNK] ),
			            DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth )
			        ),
			        "PDLCount",
			            CALCULATE (
			                DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ),
			                DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth ),
			                'sales_m_pdl'[Sales] <> 0
			            )
			    )
			RETURN
			STDEVX.P ( CustomersTTM, [PDLCount] )
		lineageTag: ed8ece35-67d5-4aeb-acc9-58f830f2d915

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Count TTM - Avg' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartDate = EDATE(EndMonth, -11)
			VAR CustomersTTM =
			    ADDCOLUMNS (
			        CALCULATETABLE (
			            VALUES ( 'sales_m_pdl'[CustomerNK] ),
			            DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth )
			        ),
			        "PDLCount",
			            CALCULATE (
			                DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ),
			                DATESBETWEEN ( 'dim_month'[MonthEnd], StartDate, EndMonth ),
			                'sales_m_pdl'[Sales] <> 0
			            )
			    )
			RETURN
			AVERAGEX ( CustomersTTM, [PDLCount] )
		lineageTag: f5ea233a-6888-4092-a637-3f793724e230

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PL Sales TTM' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartMonth = EDATE(EndMonth, -11)
			RETURN
			CALCULATE(
			    SUM(FACT_SALES_MONTH[ResExt]),
			    DATESBETWEEN('dim_month'[MonthEnd], StartMonth, EndMonth)
			)
		lineageTag: 1bad7bb2-aedd-40ce-9158-4a71a0df6ce8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PL Sales Prev12M' =
			
			VAR EndMonth      = MAX('dim_month'[MonthEnd])
			VAR StartPrev     = EDATE(EndMonth, -23)
			VAR EndPrev       = EDATE(EndMonth, -12)
			RETURN
			CALCULATE(
			    SUM(FACT_SALES_MONTH[ResExt]),
			    DATESBETWEEN('dim_month'[MonthEnd], StartPrev, EndPrev)
			)
		lineageTag: c875c428-3897-42c7-88b4-018e8d451f24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Growth Trend Index (PL)' =
			
			DIVIDE( [PL Sales TTM] - [PL Sales Prev12M], [PL Sales Prev12M] )
		lineageTag: d7873668-8764-4f41-9f0e-e8618775656c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Volatility Index (PL, 12M)' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartMonth = EDATE(EndMonth, -11)
			VAR Series =
			    ADDCOLUMNS(
			        DATESBETWEEN('dim_month'[MonthEnd], StartMonth, EndMonth),
			        "Sales", CALCULATE( SUM(FACT_SALES_MONTH[ResExt]) )
			    )
			VAR MeanSales = AVERAGEX(Series, [Sales])
			VAR StdSales  = STDEVX.P(Series, [Sales])
			RETURN DIVIDE(StdSales, MeanSales, 0)
		lineageTag: 075bb14f-5784-42b7-9eab-3f1114600f05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Continuity Index (PL, 12M)' =
			
			VAR EndMonth  = MAX('dim_month'[MonthEnd])
			VAR StartMonth = EDATE(EndMonth, -11)
			VAR ActiveMonths =
			    CALCULATE(
			        DISTINCTCOUNT('dim_month'[MonthEnd]),
			        FILTER(
			            ADDCOLUMNS(
			                'dim_month',
			                "@Sales", CALCULATE(SUM(FACT_SALES_MONTH[ResExt]))
			            ),
			            [@Sales] > 0
			        ),
			        DATESBETWEEN('dim_month'[MonthEnd], StartMonth, EndMonth)
			    )
			RETURN DIVIDE(ActiveMonths, 12)
		lineageTag: a181ccda-cdc3-4991-aacb-2d8344aad78d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Stability Index (PL, 12M)' =
			
			VAR EndMonth = MAX('dim_month'[MonthEnd])
			VAR StartMonth = EDATE(EndMonth, -11)
			VAR CustSeries =
			    ADDCOLUMNS(
			        DATESBETWEEN('dim_month'[MonthEnd], StartMonth, EndMonth),
			        "CustCount", CALCULATE(DISTINCTCOUNT(FACT_SALES_MONTH[CustomerNK]))
			    )
			VAR MeanCust = AVERAGEX(CustSeries, [CustCount])
			VAR StdCust  = STDEVX.P(CustSeries, [CustCount])
			RETURN 1 - DIVIDE(StdCust, MeanCust, 0)
		lineageTag: a2c245e5-b551-44c4-8f25-56ce69758864

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PL Units TTM (from fact_clean_monthed)' =
			
			VAR EndMonth =
			    CALCULATE(
			        MAX('dim_month'[MonthEnd]),
			        ALL('dim_month')
			    )
			VAR StartMonth = EDATE(EndMonth, -11)
			RETURN
			CALCULATE(
			    SUM('FACT_SALES_MONTH'[Qty]),
			    DATESBETWEEN('FACT_SALES_MONTH'[MonthEnd], StartMonth, EndMonth)
			)
		lineageTag: f60bbca5-499f-45ed-8cf4-8dd1692aa7a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Growth Trend Index (PL, 12M)' =
			
			VAR EndMonth = MAX('dim_month'[MonthEnd])
			VAR StartMonth = EDATE(EndMonth, -11)
			VAR Series =
			    ADDCOLUMNS(
			        DATESBETWEEN('dim_month'[MonthEnd], StartMonth, EndMonth),
			        "Sales", CALCULATE(SUM(FACT_SALES_MONTH[ResExt]))
			    )
			VAR FirstMonthSales = MINX(Series, [Sales])
			VAR LastMonthSales  = MAXX(Series, [Sales])
			RETURN DIVIDE(LastMonthSales - FirstMonthSales, FirstMonthSales, 0)
		lineageTag: c7618ecc-6c46-47df-bb9b-8dde7fa32114

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Relative Growth Index (PL)' =
			
			VAR PLGrowth =
			    [Growth Trend Index (PL, 12M)]
			VAR AvgGrowth =
			    CALCULATE(
			        AVERAGEX(
			            VALUES('product_quadrant_month'[ProductLine]),
			            [Growth Trend Index (PL, 12M)]
			        ),
			        ALL('product_quadrant_month')
			    )
			RETURN
			    PLGrowth - AvgGrowth
		lineageTag: a73dd92e-3be6-4c41-8c00-19041683659c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales TTM' = ```
			
			VAR EndMonth   = CALCULATE ( MAX ( 'dim_month'[MonthEnd] ), ALL ( 'dim_month' ) )
			VAR StartMonth = EDATE ( EndMonth, -11 )
			RETURN
			CALCULATE ( [Sales], DATESBETWEEN ( 'dim_month'[MonthEnd], StartMonth, EndMonth ) )
			
			```
		lineageTag: 15049b58-ffb0-44c0-9ffc-07e3a7860438

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CAGR Sales (Calendar, 2023→Current)' =
			
			VAR StartYear = 2023
			VAR EndYear   = YEAR ( CALCULATE ( MAX ( 'dim_month'[MonthEnd] ), ALL ( 'dim_month' ) ) )
			VAR StartVal  =
			    CALCULATE (
			        [Sales],
			        FILTER ( ALL ( 'dim_month' ), 'dim_month'[Year] = StartYear )
			    )
			VAR EndVal    =
			    CALCULATE (
			        [Sales],
			        FILTER ( ALL ( 'dim_month' ), 'dim_month'[Year] = EndYear )
			    )
			VAR NumYears  = EndYear - StartYear
			RETURN
			IF (
			    NumYears > 0 && StartVal > 0 && EndVal > 0,
			    POWER ( DIVIDE ( EndVal, StartVal ), 1 / NumYears ) - 1
			)
		lineageTag: d0c3272c-7d11-4c21-9623-7152fe6c7370

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Sales Share % (TTM)' =
			
			VAR EndMonth =
			    CALCULATE ( MAX ( 'dim_month'[MonthEnd] ), ALL ( 'dim_month' ) )
			VAR StartMonth =
			    EDATE ( EndMonth, -11 )
			VAR Sales_PDL =
			    CALCULATE (
			        SUM ( FACT_SALES_MONTH[ResExt] ),
			        DATESBETWEEN ( 'dim_month'[MonthEnd], StartMonth, EndMonth )
			    )
			VAR Sales_All =
			    CALCULATE (
			        SUM ( FACT_SALES_MONTH[ResExt] ),
			        DATESBETWEEN ( 'dim_month'[MonthEnd], StartMonth, EndMonth ),
			        ALL ( FACT_SALES_MONTH )
			    )
			RETURN
			DIVIDE ( Sales_PDL, Sales_All, 0 )
		lineageTag: f03026a8-09d8-4dac-82fe-38f4978eaacc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Repurchase Rate % (PL, 12M)' =
			
			VAR EndMonth   = CALCULATE(MAX('dim_month'[MonthEnd]), ALLSELECTED('dim_month'))
			VAR StartMonth = EDATE(EndMonth, -11)
			
			-- 近 12M 的交易窗
			VAR SalesWindow =
			    FILTER(
			        FACT_SALES_MONTH,
			        FACT_SALES_MONTH[MonthEnd] >= StartMonth &&
			        FACT_SALES_MONTH[MonthEnd] <= EndMonth &&
			        FACT_SALES_MONTH[ResExt] > 0
			    )
			
			-- 每位客戶在近 12M 的「有購買月份數」
			VAR PerCustMonths =
			    SUMMARIZE(
			        SalesWindow,
			        FACT_SALES_MONTH[CustomerNK],
			        "__ActiveMonths", DISTINCTCOUNT(FACT_SALES_MONTH[MonthEnd])
			    )
			
			-- 回購客：有購買月份數 ≥ 2 的客戶
			VAR RepeatCust =
			    FILTER(PerCustMonths, [__ActiveMonths] >= 2)
			
			-- 總金額（近 12M, 保留目前的 ProductLine 等脈絡）
			VAR SalesTotal =
			    CALCULATE(SUM(FACT_SALES_MONTH[ResExt]), SalesWindow)
			
			-- 回購客金額（用 TREATAS 把回購客名單套回事實表）
			VAR SalesRepeat =
			    CALCULATE(
			        SUM(FACT_SALES_MONTH[ResExt]),
			        SalesWindow,
			        TREATAS(
			            SELECTCOLUMNS(RepeatCust, "CustomerNK", [CustomerNK]),
			            FACT_SALES_MONTH[CustomerNK]
			        )
			    )
			
			RETURN DIVIDE(SalesRepeat, SalesTotal, 0)
		lineageTag: 1d07196a-c5bc-4e7c-90de-a0450507173a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales TTM (12M)' =
			
			VAR EndMonth = CALCULATE(MAX('dim_month'[MonthEnd]), ALLSELECTED('dim_month'))
			VAR StartMonth = EDATE(EndMonth, -11)
			RETURN
			CALCULATE(
			    SUM(FACT_SALES_MONTH[ResExt]),
			    FACT_SALES_MONTH[MonthEnd] >= StartMonth &&
			    FACT_SALES_MONTH[MonthEnd] <= EndMonth
			)
		lineageTag: 48fd182e-1dfb-4bca-bd68-41cdc45509e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active Customers (12M)' =
			
			VAR EndMonth =
			    CALCULATE ( MAX ( 'dim_month'[MonthEnd] ), ALLSELECTED ( 'dim_month' ) )
			VAR StartMonth = EDATE ( EndMonth, -11 )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( FACT_SALES_MONTH[CustomerNK] ),
			    FACT_SALES_MONTH[MonthEnd] >= StartMonth &&
			    FACT_SALES_MONTH[MonthEnd] <= EndMonth &&
			    FACT_SALES_MONTH[ResExt] > 0
			)
		formatString: 0
		lineageTag: 1bd28fbc-e291-4a44-8a7e-4175e1a8c07a

		changedProperty = IsHidden

	measure 'Ref MonthEnd' =
			
			VAR fromSlicer =
			    CALCULATE ( MAX ( 'DIM_MONTH'[MonthEnd] ), ALLSELECTED ( 'DIM_MONTH'[MonthEnd] ) )
			RETURN
			COALESCE ( fromSlicer, CALCULATE ( MAX ( 'DIM_MONTH'[MonthEnd] ), ALL ( 'DIM_MONTH' ) ) )
		formatString: General Date
		lineageTag: 7ff3f6b0-ed48-4167-99d6-23d5aafd87c7

	measure 'Customer 12M Purchase Amount' =
			
			VAR refM   = [Ref MonthEnd]
			VAR startM = EOMONTH ( refM, -11 )
			VAR T12M =
			    CALCULATETABLE (
			        FACT_SALES_MONTH,
			        ALL ( 'DIM_MONTH' ),                          -- 徹底移除 slicer 的日期過濾
			        REMOVEFILTERS ( FACT_SALES_MONTH[MonthEnd] ),
			        FACT_SALES_MONTH[MonthEnd] >= startM,
			        FACT_SALES_MONTH[MonthEnd] <= refM,
			        FACT_SALES_MONTH[ResExt] > 0
			    )
			RETURN
			SUMX ( T12M, FACT_SALES_MONTH[ResExt] )
		lineageTag: 9e81fab6-2491-4cbf-b971-a150c6c067eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer 12M Distinct Months' =
			
			VAR refM   = [Ref MonthEnd]
			VAR startM = EOMONTH ( refM, -11 )
			VAR T12M =
			    CALCULATETABLE (
			        FACT_SALES_MONTH,
			        ALL ( 'DIM_MONTH' ),
			        REMOVEFILTERS ( FACT_SALES_MONTH[MonthEnd] ),
			        FACT_SALES_MONTH[MonthEnd] >= startM,
			        FACT_SALES_MONTH[MonthEnd] <= refM,
			        FACT_SALES_MONTH[ResExt] > 0
			    )
			RETURN
			COUNTROWS ( SUMMARIZE ( T12M, FACT_SALES_MONTH[CustomerNK], FACT_SALES_MONTH[MonthEnd] ) )
		formatString: 0
		lineageTag: a10c9cce-7bef-4aaf-85aa-fb9f1727d8e8

	measure 'Customer 12M Distinct PDLs' =
			
			VAR refM   = [Ref MonthEnd]
			VAR startM = EOMONTH ( refM, -11 )
			VAR T12M =
			    CALCULATETABLE (
			        FACT_SALES_MONTH,
			        ALL ( 'DIM_MONTH' ),
			        REMOVEFILTERS ( FACT_SALES_MONTH[MonthEnd] ),
			        FACT_SALES_MONTH[MonthEnd] >= startM,
			        FACT_SALES_MONTH[MonthEnd] <= refM,
			        FACT_SALES_MONTH[ResExt] > 0
			    )
			RETURN
			COUNTROWS ( SUMMARIZE ( T12M, FACT_SALES_MONTH[CustomerNK], FACT_SALES_MONTH[ProductLine] ) )
		formatString: 0
		lineageTag: 8ee135e1-22d0-4b9d-bbc6-c024bc9f7bad

	measure 'Title Period' =
			
			VAR refM   = [Ref MonthEnd]
			VAR startM = EOMONTH ( refM, -11 )
			RETURN
			"Period: " & FORMAT ( startM, "yyyy-MM" ) & " ~ " & FORMAT ( refM, "yyyy-MM" )
		lineageTag: 58ce5810-6ba3-4405-aad0-28667c654beb

	measure 'Customer Count (@Selected Month)' =
			
			VAR SelMonth = MAX ( 'dim_month'[MonthEnd] )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    KEEPFILTERS ( 'customer_monthlyrfm'[MonthEnd] = SelMonth )
			)
		formatString: 0
		lineageTag: 3d549078-f617-42a4-8a3a-acbceb8291a4

	measure 'GM 12M (Selected)' = [ResExt 12M]
		lineageTag: 5d8a3b82-1026-4ccd-a24b-921e508fc9d7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GM 12M (Prev)' =
			
			VAR EndMonthPrev   = EDATE ( MAX('dim_month'[MonthEnd]), -12 )
			VAR StartMonthPrev = EDATE ( EndMonthPrev, -11 )
			RETURN
			CALCULATE (
			    SUM ( 'FACT_SALES_MONTH'[ResExt] ),
			    DATESBETWEEN ( 'dim_month'[MonthEnd], StartMonthPrev, EndMonthPrev )
			)
		lineageTag: 38498b37-4e33-4650-8bb9-bea30984f9fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GM 12M Δ' =
			
			[GM 12M (Selected)] - [GM 12M (Prev)]
		lineageTag: cb132a96-1080-46f3-94b6-9476e976ac86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Repurchase_Customers =
			
			CALCULATE(
			    DISTINCTCOUNT(FACT_SALES_MONTH[CustomerNK]),
			    FILTER(VALUES(FACT_SALES_MONTH[CustomerNK]),
			        CALCULATE([GM (Rolling12M)]) > 0
			    )
			)
		formatString: 0
		lineageTag: c0df4e56-b8f9-47e2-83ad-18069cd86da8

	measure Repurchase_Customers_PDL_GE2 =
			
			CALCULATE(
			    DISTINCTCOUNT(FACT_SALES_MONTH[CustomerNK]),
			    FILTER(VALUES(FACT_SALES_MONTH[CustomerNK]),
			        CALCULATE( DISTINCTCOUNT(FACT_SALES_MONTH[ProductLine]),
			                   DATESINPERIOD(DIM_MONTH[MonthEnd], MAX(DIM_MONTH[MonthEnd]), -12, MONTH)) >= 2
			        &&
			        CALCULATE([GM (Rolling12M)]) > 0
			    )
			)
		formatString: 0
		lineageTag: dc256ab1-1a3c-4770-912a-02bef319767b

	measure CrossCategory_Rate_12M =
			
			DIVIDE([Purchasing_Customers_PDL_GE2_12M], [Purchasing_Customers_12M])
		lineageTag: 3fb8f8c4-73df-40f3-a963-d6e1da3eed3e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Purchasing_Customers_12M =
			
			VAR _end = MAX(DIM_MONTH[MonthEnd])
			RETURN
			CALCULATE(
			    DISTINCTCOUNT(FACT_SALES_MONTH[CustomerNK]),
			    FILTER(
			        VALUES(FACT_SALES_MONTH[CustomerNK]),
			        CALCULATE(
			            SUM(FACT_SALES_MONTH[ResExt]),
			            DATESINPERIOD(DIM_MONTH[MonthEnd], _end, -12, MONTH)
			        ) > 0
			    )
			)
		formatString: 0
		lineageTag: e1c3483d-a056-48c3-bd22-bb074797489f

	measure Purchasing_Customers_PDL_GE2_12M =
			
			VAR _end = MAX(DIM_MONTH[MonthEnd])
			RETURN
			CALCULATE(
			    DISTINCTCOUNT(FACT_SALES_MONTH[CustomerNK]),
			    FILTER(
			        VALUES(FACT_SALES_MONTH[CustomerNK]),
			        CALCULATE(
			            DISTINCTCOUNT(FACT_SALES_MONTH[ProductLine]),
			            DATESINPERIOD(DIM_MONTH[MonthEnd], _end, -12, MONTH)
			        ) >= 2
			        &&
			        CALCULATE(
			            SUM(FACT_SALES_MONTH[ResExt]),
			            DATESINPERIOD(DIM_MONTH[MonthEnd], _end, -12, MONTH)
			        ) > 0
			    )
			)
		formatString: 0
		lineageTag: 2aa14925-4141-4304-aded-5e679d9b2226

	measure 'Active Customers (at Selected Month)' = ```
			
			VAR m = [Selected MonthEnd]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			    'customer_monthlyrfm'[MonthEnd] = m,
			    KEEPFILTERS('customer_monthlyrfm'[RecencySegment] = "Active")
			)
			
			```
		formatString: 0
		lineageTag: e3cb8632-437e-4605-a9b4-438c94d182ac

	measure 'Selected MonthEnd' =
			
			VAR mSel = SELECTEDVALUE ( 'customer_monthlyrfm'[MonthEnd] )
			RETURN COALESCE ( mSel, [Anchor_CurrentMonth] )
		formatString: General Date
		lineageTag: 03cd11f4-28e4-452d-b7bf-5d03f328b980

	measure 'Longtail NEW Customers (at Selected Month)' =
			
			VAR m = [Selected MonthEnd]
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    'customer_monthlyrfm'[MonthEnd] = m,
			    KEEPFILTERS (
			        'customer_monthlyrfm'[RFM_Segment] = "Active_Low_Low"
			            || 'customer_monthlyrfm'[RFM_NameZh] = "長尾新客"
			            || 'customer_monthlyrfm'[RFM_NameEn] = "New Tail Customer"
			    )
			)
		formatString: 0
		lineageTag: 16b35d54-1b00-4ab5-bd51-4f0f4f429df8

	measure 'Longtail NEW Share (% of Active, Selected Month)' =
			
			DIVIDE (
			    [Longtail NEW Customers (at Selected Month)],
			    [Active Customers (at Selected Month)]
			)
		lineageTag: 1f6af6c8-cc01-4d85-aa1b-d03d87593ecb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active-Longtail Customers (at Selected Month)' =
			
			VAR m = [Selected MonthEnd]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			    'customer_monthlyrfm'[MonthEnd] = m,
			    KEEPFILTERS('customer_monthlyrfm'[RecencySegment] = "Active"),
			    KEEPFILTERS('customer_monthlyrfm'[FrequencySegment] = "Low")
			)
		formatString: 0
		lineageTag: 0d61756b-9422-4a2c-a1bd-7155de1163e1

	measure 'Active-Longtail Share (% of Active)' =
			
			DIVIDE(
			    [Active-Longtail Customers (at Selected Month)],
			    [Active Customers (at Selected Month)]
			)
		lineageTag: 7b097eba-9619-4879-8e7d-a2ebb58cb804

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active-Longtail GM Share (% of Active)' =
			
			VAR m = [Selected MonthEnd]   -- 你前面已定義過的 anchor month DAX
			VAR TotalActiveGM =
			    CALCULATE(
			        SUM('customer_monthlyrfm'[AnnualValue]),
			        'customer_monthlyrfm'[MonthEnd] = m,
			        KEEPFILTERS('customer_monthlyrfm'[RecencySegment] = "Active")
			    )
			VAR LongtailGM =
			    CALCULATE(
			        SUM('customer_monthlyrfm'[AnnualValue]),
			        'customer_monthlyrfm'[MonthEnd] = m,
			        KEEPFILTERS('customer_monthlyrfm'[RecencySegment] = "Active"),
			        KEEPFILTERS('customer_monthlyrfm'[FrequencySegment] = "Low")
			    )
			RETURN
			DIVIDE(LongtailGM, TotalActiveGM)
		lineageTag: 960334ec-5afa-40fe-bdc4-152cb67ca038

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active-Longtail Share (% of Total Customers)' =
			
			VAR m = [Selected MonthEnd]
			VAR TotalCustomers =
			    CALCULATE(
			        DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			        'customer_monthlyrfm'[MonthEnd] = m
			    )
			VAR LongtailCustomers =
			    CALCULATE(
			        DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			        'customer_monthlyrfm'[MonthEnd] = m,
			        KEEPFILTERS('customer_monthlyrfm'[RecencySegment] = "Active"),
			        KEEPFILTERS('customer_monthlyrfm'[FrequencySegment] = "Low")
			    )
			RETURN
			DIVIDE(LongtailCustomers, TotalCustomers)
		lineageTag: 6600471e-269f-4bb2-b685-57fad8fa72e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active-Longtail Growth YoY (%)' =
			
			VAR __m      = [Selected MonthEnd]
			VAR __mPrev  = EDATE(__m, -12)
			VAR __currN  =
			    CALCULATE(
			        DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			        'customer_monthlyrfm'[MonthEnd] = __m,
			        'customer_monthlyrfm'[RecencySegment] = "Active",
			        'customer_monthlyrfm'[FrequencySegment] = "Low"
			    )
			VAR __prevN  =
			    CALCULATE(
			        DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			        'customer_monthlyrfm'[MonthEnd] = __mPrev,
			        'customer_monthlyrfm'[RecencySegment] = "Active",
			        'customer_monthlyrfm'[FrequencySegment] = "Low"
			    )
			RETURN
			DIVIDE(__currN - __prevN, __prevN)
		lineageTag: 7fe0ba35-182f-4e86-b350-fabe12d06581

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'New Customers (12M)' =
			
			VAR m = MAX('customer_monthlyrfm'[MonthEnd])
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			    KEEPFILTERS('customer_monthlyrfm'[IsNew] = TRUE()),
			    DATESINPERIOD('customer_monthlyrfm'[MonthEnd], m, -12, MONTH)
			)
		formatString: 0
		lineageTag: 94926de1-81d3-4b7b-9436-6a7572cd884d

	measure 'Lost Customers (to Dormant, 12M)' =
			
			VAR m = MAX('customer_monthlyrfm'[MonthEnd])
			RETURN
			SUMX(
			    DATESINPERIOD('customer_monthlyrfm'[MonthEnd], m, -12, MONTH),
			    CALCULATE(
			        [Lost to Dormant (Monthly, Distinct)]
			    )
			)
		formatString: 0
		lineageTag: ea02b9e0-c9ad-41eb-ab19-31cb55c2f29b

	measure 'NLR (12M)' =
			
			DIVIDE ( [New Customers (12M Flow)], [Lost to Dormant (12M Flow)] )
		lineageTag: d0d70047-d18d-49b9-b980-71431131f6e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Active+Sleep Customers (Selected)' =
			
			VAR m = [Anchor_CurrentMonth]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    'customer_monthlyrfm'[MonthEnd] = m,
			    KEEPFILTERS ( 'customer_monthlyrfm'[RecencySegment] IN { "Active", "Sleep" } )
			)
		formatString: 0
		lineageTag: 70c0cd4f-11ae-4b9a-9e63-b6592ae28ec0

	measure 'Active+Sleep Customers (LY)' =
			
			VAR m = [Anchor_CurrentMonth]
			VAR m_prev = EDATE ( m, -12 )
			RETURN
			CALCULATE(
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    'customer_monthlyrfm'[MonthEnd] = m_prev,
			    KEEPFILTERS ( 'customer_monthlyrfm'[RecencySegment] IN { "Active", "Sleep" } )
			)
		formatString: 0
		lineageTag: 737f5c7c-4b75-4ee0-ad66-69ecb4713117

	measure 'Active+Sleep Customers YoY (%)' =
			
			VAR cur = [Active+Sleep Customers (Selected)]
			VAR ly  = [Active+Sleep Customers (LY)]
			RETURN
			IF (
			    NOT ISBLANK ( cur ) && NOT ISBLANK ( ly ),
			    DIVIDE ( cur - ly, ly ),
			    BLANK ()
			)
		lineageTag: 5cd09b48-d5d2-4228-97db-6ad5947056a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'New Customers (12M) LY' =
			
			VAR m          = [Selected MonthEnd]
			VAR startPrev  = EOMONTH ( m, -24 ) + 1
			VAR endPrev    = EOMONTH ( m, -12 )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    FILTER (
			        ALL ( 'customer_monthlyrfm'[MonthEnd] ),
			        'customer_monthlyrfm'[MonthEnd] >= startPrev
			            && 'customer_monthlyrfm'[MonthEnd] <= endPrev
			    ),
			    KEEPFILTERS ( 'customer_monthlyrfm'[IsNew] = TRUE () )
			)
		formatString: 0
		lineageTag: a27cccf2-b48d-49bc-8d4c-33a71d7c9630

	measure 'New Customers YoY % (12M)' =
			
			VAR cur = [New Customers (12M)]
			VAR ly  = [New Customers (12M) LY]
			RETURN IF ( NOT ISBLANK ( ly ), DIVIDE ( cur - ly, ly ) )
		lineageTag: 0188cace-20a2-49b1-897f-3f030061e028

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'New Customers GM Share (12M, %)' =
			
			VAR m      = [Selected MonthEnd]
			VAR startD = EOMONTH ( m, -12 ) + 1
			VAR endD   = m
			VAR newGM =
			    CALCULATE (
			        SUM ( 'customer_monthlyrfm'[Sales12M] ),
			        FILTER (
			            ALL ( 'customer_monthlyrfm'[MonthEnd] ),
			            'customer_monthlyrfm'[MonthEnd] >= startD
			                && 'customer_monthlyrfm'[MonthEnd] <= endD
			        ),
			        KEEPFILTERS ( 'customer_monthlyrfm'[IsNew] = TRUE () )
			    )
			VAR totalGM =
			    CALCULATE (
			        SUM ( 'customer_monthlyrfm'[Sales12M] ),
			        FILTER (
			            ALL ( 'customer_monthlyrfm'[MonthEnd] ),
			            'customer_monthlyrfm'[MonthEnd] >= startD
			                && 'customer_monthlyrfm'[MonthEnd] <= endD
			        )
			    )
			RETURN
			DIVIDE ( newGM, totalGM )
		lineageTag: 9f6ef203-455c-40e3-b1d0-a76bede82d7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Customer Value (12M)' =
			
			VAR m = [Selected MonthEnd]
			VAR customers =
			    CALCULATETABLE(
			        VALUES('customer_monthlyrfm'[CustomerNK]),
			        'customer_monthlyrfm'[MonthEnd] = m,
			        'customer_monthlyrfm'[AnnualValue] > 0
			    )
			VAR totalGM =
			    CALCULATE(
			        SUM('customer_monthlyrfm'[AnnualValue]),
			        'customer_monthlyrfm'[MonthEnd] = m,
			        'customer_monthlyrfm'[AnnualValue] > 0
			    )
			VAR custCount = COUNTROWS(customers)
			RETURN
			DIVIDE(totalGM, custCount)
		lineageTag: fb053fbe-4fcc-43f4-b8fe-0d1b907bd9ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Customer Value (12M)' =
			
			VAR m = [Selected MonthEnd]
			VAR base =
			    CALCULATETABLE(
			        SUMMARIZE(
			            'customer_monthlyrfm',
			            'customer_monthlyrfm'[CustomerNK],
			            "GM12", MAX('customer_monthlyrfm'[AnnualValue])
			        ),
			        KEEPFILTERS('customer_monthlyrfm'[MonthEnd] = m),
			        KEEPFILTERS('customer_monthlyrfm'[AnnualValue] > 0)
			    )
			RETURN
			PERCENTILEX.INC(base, [GM12], 0.5)
		lineageTag: bef11560-6ffd-46fc-8a9d-c0b087d28479

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg PDL Count (12M)' =
			
			VAR m     = [Selected MonthEnd]
			VAR win12 = DATESINPERIOD ( 'sales_m_pdl'[MonthEnd], m, -12, MONTH )
			
			-- 12M 期間的 sales_m_pdl，並把目前視圖的 Customer/Region/Channel 篩選投射過來
			VAR scoped12m =
			    CALCULATETABLE (
			        FILTER (
			            'sales_m_pdl',
			            'sales_m_pdl'[MonthEnd] IN win12
			                && 'sales_m_pdl'[Sales] <> 0       -- 或改成 GM > 0 也可
			        ),
			        TREATAS ( VALUES ( 'customer_monthlyrfm'[CustomerNK] ), 'sales_m_pdl'[CustomerNK] ),
			        TREATAS ( VALUES ( 'customer_monthlyrfm'[GeoGroup]   ), 'sales_m_pdl'[GeoGroup]   ),
			        TREATAS ( VALUES ( 'customer_monthlyrfm'[DistName]   ), 'sales_m_pdl'[DistName]   )
			    )
			
			-- 以客戶為粒度，計算該客戶在 12M 內的不重複 PDL 數
			VAR per_customer =
			    SUMMARIZE (
			        scoped12m,
			        'sales_m_pdl'[CustomerNK],
			        "PDL_Count", CALCULATE ( DISTINCTCOUNT ( 'sales_m_pdl'[ProductLine] ) )
			    )
			
			VAR customers = COUNTROWS ( per_customer )
			VAR totalPDL  = SUMX ( per_customer, [PDL_Count] )
			RETURN
			DIVIDE ( totalPDL, customers )
		lineageTag: de72e73d-e4ac-47d9-952c-4b8da5711b29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Value Maturity (12M)' =
			
			VAR m =
			    [Selected MonthEnd]
			VAR CustSet =
			    CALCULATETABLE (
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] ),
			        'customer_monthlyrfm'[MonthEnd] = m,
			        KEEPFILTERS ( 'customer_monthlyrfm'[FrequencySegment] IN { "Mid", "High" } ),
			        KEEPFILTERS ( 'customer_monthlyrfm'[AnnualValue] > 0 )
			    )
			RETURN
			AVERAGEX ( CustSet, [GM 12M] )
		lineageTag: 3810d731-38df-47a7-b79d-f75d0a1f550a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'New Customers (Monthly, Distinct)' =
			
			VAR m = [Selected MonthEnd]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			    'customer_monthlyrfm'[IsNew] = TRUE(),
			    YEAR('customer_monthlyrfm'[MonthEnd]) = YEAR(m) &&
			    MONTH('customer_monthlyrfm'[MonthEnd]) = MONTH(m)
			)
		formatString: 0
		lineageTag: 44cba368-f24d-4edb-bf20-76240f238a3e

	measure 'Sleep Customers (Monthly, Distinct)' =
			
			CALCULATE(
			    DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			    KEEPFILTERS('customer_monthlyrfm'[RecencySegment] = "Sleep")
			)
		formatString: 0
		lineageTag: e668aefb-0443-4531-94b6-78f957f942bd

	measure 'Lost to Dormant (Monthly, Distinct)' =
			
			VAR m      = MAX ( 'customer_monthlyrfm'[MonthEnd] )
			VAR m_prev = EOMONTH ( m, -1 )
			RETURN
			IF (
			    ISBLANK ( m_prev ),        -- 沒有上一月就不要算（或用 0）
			    BLANK (),
			    SUMX (
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] ),
			        VAR CurrSeg =
			            CALCULATE (
			                SELECTEDVALUE ( 'customer_monthlyrfm'[RecencySegment] ),
			                'customer_monthlyrfm'[MonthEnd] = m
			            )
			        VAR PrevSeg =
			            CALCULATE (
			                SELECTEDVALUE ( 'customer_monthlyrfm'[RecencySegment] ),
			                'customer_monthlyrfm'[MonthEnd] = m_prev
			            )
			        -- 必須「本月 Dormant」且「上一月有資料，且上一月不是 Dormant」
			        RETURN IF ( CurrSeg = "Dormant" && NOT ISBLANK ( PrevSeg ) && PrevSeg <> "Dormant", 1, 0 )
			    )
			)
		formatString: 0
		lineageTag: 7067640d-eef0-4a36-a3d7-3976c2e0557e

	measure 'Dormant Customers (Distinct)' =
			
			VAR m = [Selected MonthEnd]
			RETURN
			CALCULATE(
			    DISTINCTCOUNT ( 'customer_monthlyrfm'[CustomerNK] ),
			    'customer_monthlyrfm'[MonthEnd] = m,
			    'customer_monthlyrfm'[RecencySegment] = "Dormant"
			)
		formatString: 0
		lineageTag: d8a978cc-2e2f-4204-b665-012b576889c4

	measure 'Lost to Dormant (Monthly, Net Adds)' =
			
			VAR m      = [Selected MonthEnd]
			VAR m_prev = EDATE(m, -1)
			VAR cur =
			    CALCULATE(
			        DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			        'customer_monthlyrfm'[RecencySegment] = "Dormant",
			        YEAR('customer_monthlyrfm'[MonthEnd]) = YEAR(m) &&
			        MONTH('customer_monthlyrfm'[MonthEnd]) = MONTH(m)
			    )
			VAR prev =
			    CALCULATE(
			        DISTINCTCOUNT('customer_monthlyrfm'[CustomerNK]),
			        'customer_monthlyrfm'[RecencySegment] = "Dormant",
			        YEAR('customer_monthlyrfm'[MonthEnd]) = YEAR(m_prev) &&
			        MONTH('customer_monthlyrfm'[MonthEnd]) = MONTH(m_prev)
			    )
			RETURN
			COALESCE(cur, 0) - COALESCE(prev, 0)
		formatString: 0
		lineageTag: 5cb5adaa-6885-4e59-b9bf-9cd79f3253d1

	measure 'Lost to Dormant (Monthly, Positive)' =
			
			MAX ( [Lost to Dormant (Monthly, Net Adds)], 0 )
		formatString: 0
		lineageTag: d4cc319c-7caf-47b9-ba14-06d8b3c6397f

	measure 'New Customers (12M Flow)' =
			
			VAR m = [Selected MonthEnd]
			RETURN
			CALCULATE (
			    SUMX ( VALUES('customer_monthlyrfm'[MonthEnd]), [New Customers (Monthly, Distinct)] ),
			    DATESINPERIOD ( 'customer_monthlyrfm'[MonthEnd], m, -12, MONTH )
			)
		formatString: 0
		lineageTag: 2c9a2473-e7a6-4e1a-b170-adbd17f7fde5

	measure 'Lost to Dormant (12M Flow)' =
			
			VAR m = [Selected MonthEnd]
			RETURN
			CALCULATE (
			    SUMX ( VALUES('customer_monthlyrfm'[MonthEnd]), [Lost to Dormant (Monthly, Positive)] ),
			    DATESINPERIOD ( 'customer_monthlyrfm'[MonthEnd], m, -12, MONTH )
			)
		formatString: 0
		lineageTag: 0b3f88ae-e17c-46e7-b6f9-463cb19c84c0

	measure 'PDL Penetration %' =
			
			VAR CustSet =
			    CALCULATETABLE(
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] )
			        // 這裡自動吃到畫面上的所有篩選（含 FrequencySegment、Geo、MonthEnd…）
			    )
			VAR TotalCustomers = COUNTROWS ( CustSet )
			VAR PdlBuyers =
			    CALCULATE(
			        DISTINCTCOUNT ( 'sales_m_pdl'[CustomerNK] ),
			        TREATAS ( CustSet, 'sales_m_pdl'[CustomerNK] ),
			        NOT ( ISBLANK ( 'sales_m_pdl'[Sales] ) )      -- 只算有購買的
			    )
			RETURN
			DIVIDE ( PdlBuyers, TotalCustomers )
		lineageTag: e7886801-ec07-458e-b6bd-65b9c60c0013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Avg Annual Value' =
			
			VAR CustSet =
			    CALCULATETABLE(
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] )
			    )
			VAR Buyers =
			    CALCULATE(
			        DISTINCTCOUNT ( 'sales_m_pdl'[CustomerNK] ),
			        TREATAS ( CustSet, 'sales_m_pdl'[CustomerNK] ),
			        NOT ( ISBLANK ( 'sales_m_pdl'[Sales] ) )
			    )
			VAR TotalSales =
			    CALCULATE(
			        SUM ( 'sales_m_pdl'[Sales] ),
			        TREATAS ( CustSet, 'sales_m_pdl'[CustomerNK] )
			    )
			RETURN
			DIVIDE ( TotalSales, Buyers )
		lineageTag: b8096167-1951-41fb-b4d2-dcea10553a5d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Total Sales' =
			
			VAR CustSet =
			    CALCULATETABLE(
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] )
			    )
			RETURN
			CALCULATE(
			    SUM ( 'sales_m_pdl'[Sales] ),
			    TREATAS ( CustSet, 'sales_m_pdl'[CustomerNK] )
			)
		lineageTag: d9af1d03-04ed-44ac-bf81-c1ce0b3cff55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Avg Repurchase Frequency (12M)' =
			
			VAR m =
			    [Selected MonthEnd]   -- 你的月度錨點
			VAR win12 =
			    DATESINPERIOD ( 'sales_m_pdl'[MonthEnd], m, -12, MONTH )   -- 一定要用交易表的 MonthEnd
			VAR curPDL =
			    VALUES ( 'sales_m_pdl'[ProductLine] )   -- 視覺或 slicer 當下的 PDL（支援多選）
			
			-- 先找出：在「當月 m」屬於目前 slicer 所選 FrequencySegment 的客戶集合
			VAR segCustomersAtM =
			    CALCULATETABLE (
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] ),
			        'customer_monthlyrfm'[MonthEnd] = m,
			        KEEPFILTERS ( VALUES ( 'customer_monthlyrfm'[FrequencySegment] ) )   -- 讓 slicer 決定分群
			    )
			
			-- 再找出：上述分群客戶裡面，近 12 個月「有買當前 PDL」的實際買家
			VAR buyersThisPDL =
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[CustomerNK] ),
			        KEEPFILTERS ( win12 ),
			        TREATAS ( segCustomersAtM, 'sales_m_pdl'[CustomerNK] ),
			        KEEPFILTERS ( curPDL ),
			        'sales_m_pdl'[Sales] > 0
			    )
			
			VAR buyerCount = COUNTROWS ( buyersThisPDL )
			
			-- 逐位買家計算：近 12 個月有「交易月份（去重）」的數量
			VAR totalMonthsForAllBuyers =
			    SUMX (
			        buyersThisPDL,
			        CALCULATE (
			            -- 以「月」去重（若 MonthEnd 是日級，請先在表中有 MonthEnd=月底或 MonthKey）
			            MIN ( DISTINCTCOUNT ( 'sales_m_pdl'[MonthEnd] ), 12 ),  -- 保險上限 12
			            KEEPFILTERS ( win12 ),
			            KEEPFILTERS ( curPDL ),
			            'sales_m_pdl'[Sales] > 0
			        )
			    )
			
			RETURN
			DIVIDE ( totalMonthsForAllBuyers, buyerCount )
		lineageTag: f3e22110-b07c-46cd-9834-e21a5894d7b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Cross Penetration %' =
			
			VAR _rowPDL   = SELECTEDVALUE ( 'sales_m_pdl'[ProductLine] )       -- 行（Current）
			VAR _colPDL   = SELECTEDVALUE ( 'ProductLine_Col'[ProductLine] )   -- 列（Target, 斷開表）
			
			VAR _buyers_row =
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[CustomerNK] ),
			        'sales_m_pdl'[ProductLine] = _rowPDL,
			        'sales_m_pdl'[Sales] > 0
			    )
			
			VAR _buyers_col =
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[CustomerNK] ),
			        TREATAS ( { _colPDL }, 'sales_m_pdl'[ProductLine] ),
			        'sales_m_pdl'[Sales] > 0
			    )
			
			VAR _both =
			    INTERSECT ( _buyers_row, _buyers_col )
			
			RETURN
			IF (
			    _rowPDL = _colPDL,                                -- 對角線要不要顯示自行決定
			    BLANK(),                                          -- 顯示 100% 就改成 1
			    DIVIDE ( COUNTROWS ( _both ), COUNTROWS ( _buyers_col ) )
			)
		lineageTag: 600983af-eee7-43e3-affd-4c55ec1a9581

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PDL Cross Buyer Count' =
			
			VAR _rowPDL =
			    SELECTEDVALUE ( 'sales_m_pdl'[ProductLine] )
			VAR _colPDL =
			    SELECTEDVALUE ( 'ProductLine_Col'[ProductLine] )
			
			VAR _buyers_row =
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[CustomerNK] ),
			        'sales_m_pdl'[ProductLine] = _rowPDL,
			        'sales_m_pdl'[Sales] > 0
			    )
			
			VAR _buyers_col =
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[CustomerNK] ),
			        TREATAS ( { _colPDL }, 'sales_m_pdl'[ProductLine] ),
			        'sales_m_pdl'[Sales] > 0
			    )
			
			RETURN
			COUNTROWS ( INTERSECT ( _buyers_row, _buyers_col ) )
		formatString: 0
		lineageTag: b71f2907-6ecb-4c61-8a9a-44b023de2ed7

	measure 'PDL Target Buyer Base' =
			
			VAR _colPDL =
			    SELECTEDVALUE ( 'ProductLine_Col'[ProductLine] )
			
			RETURN
			COUNTROWS (
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[CustomerNK] ),
			        TREATAS ( { _colPDL }, 'sales_m_pdl'[ProductLine] ),
			        'sales_m_pdl'[Sales] > 0
			    )
			)
		formatString: 0
		lineageTag: 67c02e1d-30b8-408e-b116-9f85a3569101

	measure 'PDL Row Buyer Base' = ```
			
			VAR _rowPDL =
			    SELECTEDVALUE ( 'sales_m_pdl'[ProductLine] )
			RETURN
			COUNTROWS (
			    CALCULATETABLE (
			        VALUES ( 'sales_m_pdl'[CustomerNK] ),
			        'sales_m_pdl'[ProductLine] = _rowPDL,
			        'sales_m_pdl'[Sales] > 0
			    )
			)
			
			```
		formatString: 0
		lineageTag: 3ce40705-654c-4a96-bc00-c098df314875

	measure 'PDL Cross Penetration (Row %)' =
			
			DIVIDE ( [PDL Cross Buyer Count], [PDL Row Buyer Base] )
		lineageTag: 5617a9ee-657d-4f3e-a6d0-3cc67c66f4c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales CY 12M' =
			
			VAR _end = [Selected MonthEnd]
			RETURN
			CALCULATE (
			    SUM ( 'pdl_month_agg'[Sales] ),
			    FILTER (
			        ALL ( 'Dim_Month' ),
			        'Dim_Month'[MonthEnd] <= _end
			            && 'Dim_Month'[MonthEnd] > EDATE ( _end, -12 )
			    )
			)
		lineageTag: 9d50e46f-0468-49fb-bc6f-ccf16b701f83

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales PY 12M' =
			
			VAR _end   = [Selected MonthEnd]
			VAR _pyEnd = EDATE ( _end, -12 )
			RETURN
			CALCULATE (
			    SUM ( 'pdl_month_agg'[Sales] ),
			    FILTER (
			        ALL ( 'Dim_Month' ),
			        'Dim_Month'[MonthEnd] <= _pyEnd
			            && 'Dim_Month'[MonthEnd] > EDATE ( _pyEnd, -12 )
			    )
			)
		lineageTag: ed26716b-9982-4826-9676-36c86a7d5c30

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Diff' = [Sales CY 12M] - [Sales PY 12M]
		lineageTag: e17ac0f4-ad9e-45f2-826d-55cd99ed39c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color by Growth' =
			
			VAR g = [RFM Sales Diff 12M]
			RETURN
			IF(
			    ISBLANK(g),
			    "#BFBFBF",             -- 灰色（無資料）
			    IF(g >= 0, "#00B050", "#E60000")
			)
		lineageTag: 95c454fe-09be-463b-9353-3b44be503418

	measure 'Sales Growth %' =
			
			DIVIDE( [Sales Diff], [Sales PY 12M] )
		lineageTag: 496ba335-e033-40e7-bb12-99d313512b64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Diff Abs' =
			
			ABS ( [Sales Diff] )
		lineageTag: 7a7b1645-0421-4831-bc6a-f91acefa53fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fact Customers' =
			
			DISTINCTCOUNT ( fact_clean[CustomerNK] )
		formatString: 0
		lineageTag: 64a8ea01-1926-42c7-ad1e-1ae0adb64241

	measure 'RFM Customers (selected month)' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( customer_monthlyrfm[CustomerNK] ),
			    customer_monthlyrfm[MonthEnd] = _selMonth
			)
		formatString: 0
		lineageTag: e73db250-ee52-4644-a37a-cd220a6f29ff

	measure 'Sales 12M (sel ME)' =
			
			VAR me =
			    MAX ( 'customer_monthlyrfm'[MonthEnd] )
			RETURN
			CALCULATE (
			    SUM ( 'customer_monthlyrfm'[Sales12M] ),
			    'customer_monthlyrfm'[MonthEnd] = me
			)
		lineageTag: 1649f484-821c-43d1-bc4f-d8a3cf884eb2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rank Customer by Sales 12M' =
			
			VAR _selME = MAX ( 'DIM_MONTH'[MonthEnd] )
			RETURN
			RANKX (
			    ALLSELECTED ( 'customer_monthlyrfm'[CustomerNK] ),
			    CALCULATE (
			        SUM ( 'customer_monthlyrfm'[Sales12M] ),
			        'customer_monthlyrfm'[MonthEnd] = _selME,
			        REMOVEFILTERS ( 'customer_monthlyrfm'[DistName] ),
			        REMOVEFILTERS ( 'customer_monthlyrfm'[GeoGroup] )
			    ),
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: 4cf005c6-e779-4fc7-a179-41d05c20fd41

	measure 'Sales Rank (sel ME)' =
			
			VAR me =
			    MAX ( 'customer_monthlyrfm'[MonthEnd] )
			RETURN
			RANKX (
			    FILTER (
			        ALLSELECTED ( 'customer_monthlyrfm' ),
			        'customer_monthlyrfm'[MonthEnd] = me
			    ),
			    [Sales 12M (sel ME)],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: d06b8e7b-8711-41c4-adca-af34d342ca0f

	measure Rank =
			
			RANKX(
			    ALLSELECTED('customer_monthlyrfm_global'[CustomerNK]),
			    CALCULATE(SUM('customer_monthlyrfm_global'[Sales12M])),
			    ,
			    DESC
			)
		lineageTag: ff60ebc4-0085-470f-9bb1-8d187677494c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pdl Monthly CV 12M' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _months12 =
			    DATESINPERIOD ( 'DIM_MONTH'[MonthEnd], _selMonth, -11, MONTH )
			
			-- 對這 12 個月逐月算「這條 ProductLine 的銷售」
			VAR _monthlyTable =
			    ADDCOLUMNS (
			        _months12,
			        "Amt",
			            CALCULATE (
			                SUM ( 'fact_clean'[ResExt] )    -- 你的實際銷售欄位
			                -- 這裡不要 REMOVEFILTERS(DIM_MONTH)
			                -- 外面的 ProductLine / GeoGroup 篩選也會一起吃進來
			            )
			    )
			VAR _avg  = AVERAGEX ( _monthlyTable, [Amt] )
			VAR _stdev = STDEVX.P ( _monthlyTable, [Amt] )
			RETURN
			IF ( _avg = 0, BLANK(), _stdev / _avg )
		lineageTag: 74c598e5-452e-4f63-8242-6deec714d5f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pdl Stability 12M' =
			
			VAR _cv = [Pdl Monthly CV 12M]
			RETURN IF ( ISBLANK ( _cv ), BLANK(), 1 / ( 1 + _cv ) )
		lineageTag: 4dcb8d8d-2e06-41b9-825f-cd51fcea7b49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cust 12M by Recency' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _start =
			    EDATE ( _selMonth, -11 )
			
			-- 這個月、目前這個 RecencySegment 底下的客戶名冊
			VAR _custList =
			    CALCULATETABLE (
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] ),
			        'customer_monthlyrfm'[MonthEnd] = _selMonth,
			        -- 很重要：吃到視覺上的 RecencySegment
			        KEEPFILTERS ( VALUES ( 'customer_monthlyrfm'[RecencySegment] ) ),
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'fact_clean'[CustomerNK] ),
			    -- 把名冊套到 fact_clean
			    TREATAS ( _custList, 'fact_clean'[CustomerNK] ),
			    -- 只看近 12M
			    'fact_clean'[POS_ShpDate] >= _start,
			    'fact_clean'[POS_ShpDate] <= _selMonth,
			    -- 不要被日曆多影響
			    REMOVEFILTERS ( 'DIM_MONTH' )
			)
		formatString: 0
		lineageTag: 892034eb-b5ee-4a9c-8ef4-16e51f8134e6

	measure 'Cust 12M by Frequency' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _start =
			    EDATE ( _selMonth, -11 )
			VAR _custList =
			    CALCULATETABLE (
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] ),
			        'customer_monthlyrfm'[MonthEnd] = _selMonth,
			        KEEPFILTERS ( VALUES ( 'customer_monthlyrfm'[FrequencySegment] ) ),
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'fact_clean'[CustomerNK] ),
			    TREATAS ( _custList, 'fact_clean'[CustomerNK] ),
			    'fact_clean'[POS_ShpDate] >= _start,
			    'fact_clean'[POS_ShpDate] <= _selMonth,
			    REMOVEFILTERS ( 'DIM_MONTH' )
			)
		formatString: 0
		lineageTag: c99b76bd-736e-47d6-b348-ae02aaa8c687

	measure 'Cust 12M by Value' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _start =
			    EDATE ( _selMonth, -11 )
			VAR _custList =
			    CALCULATETABLE (
			        VALUES ( 'customer_monthlyrfm'[CustomerNK] ),
			        'customer_monthlyrfm'[MonthEnd] = _selMonth,
			        KEEPFILTERS ( VALUES ( 'customer_monthlyrfm'[ValueSegment] ) ),
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'fact_clean'[CustomerNK] ),
			    TREATAS ( _custList, 'fact_clean'[CustomerNK] ),
			    'fact_clean'[POS_ShpDate] >= _start,
			    'fact_clean'[POS_ShpDate] <= _selMonth,
			    REMOVEFILTERS ( 'DIM_MONTH' )
			)
		formatString: 0
		lineageTag: db958eb1-1226-4c7c-9375-03ee6abf17ba

	measure 'FM Sales 12M' =
			
			VAR selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR startMonth =
			    EDATE ( selMonth, -11 )
			
			-- 現在這塊圖的 FM 分群（只看 M, F 兩軸的那欄）
			VAR curFM =
			    SELECTEDVALUE ( 'customer_monthlyrfm'[RFM_NameZh_S] )
			
			-- 沒選到分群就不要算，避免整張圖出現一筆超大
			VAR fmThisMonth =
			    CALCULATETABLE (
			        SUMMARIZE (
			            'customer_monthlyrfm',
			            'customer_monthlyrfm'[CustomerNK],
			            'customer_monthlyrfm'[DistName]
			        ),
			        'customer_monthlyrfm'[MonthEnd] = selMonth,
			        'customer_monthlyrfm'[RFM_NameZh_S] = curFM,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			IF (
			    ISBLANK ( curFM ),
			    BLANK (),
			    CALCULATE (
			        [Sales],    -- 你原本的銷售量值
			        TREATAS ( fmThisMonth, 'fact_clean'[CustomerNK], 'fact_clean'[DistName] ),
			        'fact_clean'[POS_ShpDate] >= startMonth,
			        'fact_clean'[POS_ShpDate] <= selMonth,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			)
		lineageTag: 6bf23a30-d9db-4982-944c-20cdc6fcdaad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FM Sales 12M_2' =
			
			VAR selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR startMonth =
			    EDATE ( selMonth, -11 )
			VAR curFM =
			    SELECTEDVALUE ( 'customer_monthlyrfm'[RFM_NameZh_S] )
			-- 這個月、這個 FM 的客戶×通路×月
			VAR curCustMonth =
			    CALCULATETABLE (
			        DISTINCT ( 'customer_monthlyrfm'[CustDistKeyMonth] ),
			        'customer_monthlyrfm'[MonthEnd] = selMonth,
			        'customer_monthlyrfm'[RFM_NameZh_S] = curFM,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			IF (
			    ISBLANK ( curFM ),
			    BLANK (),
			    CALCULATE (
			        SUM ( fact_clean_with_custdistkeymonth[ResExt] ),
			        TREATAS ( curCustMonth, fact_clean_with_custdistkeymonth[CustDistKeyMonth] ),
			        fact_clean_with_custdistkeymonth[MonthEnd] >= startMonth,
			        fact_clean_with_custdistkeymonth[MonthEnd] <= selMonth,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			)
		lineageTag: 161732c6-725e-444a-b0fe-5264e048184c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ResExt 12M' =
			
			VAR selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR startMonth =
			    EDATE ( selMonth, -11 )
			RETURN
			CALCULATE (
			    SUM ( FACT_SALES_MONTH[ResExt] ),
			    FACT_SALES_MONTH[MonthEnd] >= startMonth,
			    FACT_SALES_MONTH[MonthEnd] <= selMonth
			)
		lineageTag: 28f396a9-8086-4dcc-8e08-20a7180fcb9f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Qty TY 12M' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _startMonth =
			    EDATE ( _selMonth, -11 )
			RETURN
			CALCULATE (
			    SUM ( 'fact_clean'[Qty] ),
			    'fact_clean'[POS_ShpDate] >= _startMonth,
			    'fact_clean'[POS_ShpDate] <= _selMonth,
			    REMOVEFILTERS ( 'DIM_MONTH' )
			)
		formatString: 0
		lineageTag: 0b75ddb3-a74e-4c01-9021-3fa7c5fb62cb

	measure 'Product Monthly Sales' =
			
			SUM( 'fact_clean'[ResExt] )
		lineageTag: 50e6300d-6b2d-4428-b035-b617b570186b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Sales 12M' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			RETURN
			CALCULATE (
			    SUM ( 'fact_clean'[ResExt] ),                -- 你真正的銷售欄位
			    DATESINPERIOD (
			        'DIM_MONTH'[MonthEnd],
			        _selMonth,
			        -11,
			        MONTH
			    )
			)
		lineageTag: 9d3c55cc-e1b9-4602-9653-b375b7474605

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Test = [Product Monthly Sales]
		lineageTag: 52ad278c-1453-4942-9d2f-f31305262ca6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rolling 12M Months' =
			
			VAR _selMonth = MAX ( 'DIM_MONTH'[MonthEnd] )
			RETURN
			DATESINPERIOD (
			    'DIM_MONTH'[MonthEnd],
			    _selMonth,
			    -11,
			    MONTH
			)
		formatString: General Date
		lineageTag: 1dca1039-ecae-46c7-b52d-a361d6bfdd71

	measure 'Product Sales 12M Mean' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			
			VAR _months =
			    DATESINPERIOD (
			        'DIM_MONTH'[MonthEnd],
			        _selMonth,
			        -11,
			        MONTH
			    )
			RETURN
			CALCULATE (
			    AVERAGEX (
			        _months,
			        [Product Monthly Sales]
			    )
			)
		lineageTag: d3f936c1-3a60-4b8f-ba8b-a754a3702ca1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Sales 12M StdDev' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			
			VAR _months =
			    DATESINPERIOD (
			        'DIM_MONTH'[MonthEnd],
			        _selMonth,
			        -11,
			        MONTH
			    )
			RETURN
			CALCULATE (
			    STDEVX.S (
			        _months,
			        [Product Monthly Sales]
			    )
			)
		lineageTag: 9d2714c0-0c3b-4f4a-97f9-1aa5ee6b6eda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Sales 12M CV' =
			
			VAR _mean = [Product Sales 12M Mean]
			VAR _std  = [Product Sales 12M StdDev]
			RETURN
			DIVIDE ( _std, _mean )
		lineageTag: 6d84f14b-594a-444c-ac83-244c8e5c9431

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PD Stability 12M' =
			
			VAR _cv = [Product Sales 12M CV]
			RETURN
			IF ( ISBLANK( _cv ), BLANK(), 1 / (1 + _cv) )
		lineageTag: 0f65811e-3545-4d16-9983-c9514e76e246

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'One-Time Customers 12M by Product' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			
			-- 12 個月視窗
			VAR _12M =
			    DATESINPERIOD (
			        'DIM_MONTH'[MonthEnd],
			        _selMonth,
			        -11,
			        MONTH
			    )
			
			-- Step 1：在 RFM 表抓出「一次客名單」
			VAR _oneTimeCust =
			    CALCULATETABLE (
			        VALUES ( customer_monthlyrfm[CustomerNK] ),
			        customer_monthlyrfm[MonthEnd] = _selMonth,
			        customer_monthlyrfm[Freq12M]  = 1
			    )
			
			-- Step 2：回到 fact_clean，算「這些一次客」在 12M 內、
			-- 針對目前這個產品（AdjPtNo）的不重複客戶數
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( fact_clean[CustomerNK] ),
			    _12M,
			    TREATAS ( _oneTimeCust, fact_clean[CustomerNK] )
			)
		formatString: 0
		lineageTag: febbe40e-ef74-4059-97ed-07ecd6821387

	measure 'Total Customers 12M by Product' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			
			VAR _12M =
			    DATESINPERIOD (
			        'DIM_MONTH'[MonthEnd],
			        _selMonth,
			        -11,
			        MONTH
			    )
			
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( fact_clean[CustomerNK] ),
			    _12M
			)
		formatString: 0
		lineageTag: 4276a708-8307-48c7-a1d4-8cf0f1c48150

	measure 'One-Time Sales 12M by Product' =
			
			VAR _selMonth   = MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _startDate  = EDATE ( _selMonth, -11 )
			
			-- 1. 找出「這個產品」在最近 12M 內只買 1 次的客戶清單
			VAR _oneTimeCust =
			    FILTER (
			        VALUES ( 'fact_clean'[CustomerNK] ),          -- 先拿到目前產品的客戶清單
			        CALCULATE (
			            COUNTROWS ( 'fact_clean' ),              -- 這個客戶在 12M 內的交易筆數
			            'fact_clean'[POS_ShpDate] >= _startDate,
			            'fact_clean'[POS_ShpDate] <= _selMonth
			        ) = 1                                        -- 只留 1 筆的（一次客）
			    )
			
			-- 2. 用這些一次客 + 12M 日期區間，去計算銷售額
			RETURN
			CALCULATE (
			    [Sales],                                        -- 你原本的銷售金額 measure（SUM ResExt）
			    _oneTimeCust,                                   -- 只保留一次客
			    'fact_clean'[POS_ShpDate] >= _startDate,
			    'fact_clean'[POS_ShpDate] <= _selMonth
			)
		lineageTag: 4ef94361-40c8-4475-bb2a-cc9344ccd486

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distinct Customers 12M by ProductLine' = ```
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			
			VAR _startDate =
			    EDATE ( _selMonth, -11 )
			
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( 'fact_clean'[CustomerNK] ),
			    
			    -- 限制時間範圍：近 12 個月
			    'fact_clean'[POS_ShpDate] >= _startDate,
			    'fact_clean'[POS_ShpDate] <= _selMonth,
			
			    -- 限制只看目前選到的 ProductLine
			    KEEPFILTERS ( VALUES ( DIM_PRODUCT[ProductLine] ) ),
			
			    REMOVEFILTERS ( 'DIM_MONTH' )   -- 避免 Month 表切斷事實表
			)
			```
		formatString: 0
		lineageTag: 489665e8-6b2e-4bbd-9b80-76f6a24af475

	measure 'RFM Qty TY 12M' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _start =
			    EDATE ( _selMonth, -11 )
			
			-- 判斷是否為單一 RFM 群組的行
			VAR _isSingleRFM =
			    HASONEVALUE ( 'customer_monthlyrfm'[RFM_NameZh] )
			
			-- ① 單一 RFM：取得「此 RFM 在此月份的 客戶 × 通路」清單
			VAR _custChanThisRFM =
			    CALCULATETABLE (
			        SUMMARIZE (
			            'customer_monthlyrfm',
			            'customer_monthlyrfm'[CustomerNK],
			            'customer_monthlyrfm'[DistName]
			        ),
			        'customer_monthlyrfm'[MonthEnd] = _selMonth,
			        KEEPFILTERS ( VALUES ( 'customer_monthlyrfm'[RFM_NameZh] ) ),
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			
			-- ② 總計列：取得「所有 RFM 在此月份的 客戶 × 通路」清單
			VAR _custChanAllRFM =
			    CALCULATETABLE (
			        SUMMARIZE (
			            'customer_monthlyrfm',
			            'customer_monthlyrfm'[CustomerNK],
			            'customer_monthlyrfm'[DistName]
			        ),
			        'customer_monthlyrfm'[MonthEnd] = _selMonth,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			IF (
			    _isSingleRFM,
			    -- 單一分群：套用客戶 × 通路，再計算近 12M 台數
			    CALCULATE (
			        [TTLQty],
			        TREATAS ( _custChanThisRFM, 'fact_clean'[CustomerNK], 'fact_clean'[DistName] ),
			        'fact_clean'[POS_ShpDate] >= _start,
			        'fact_clean'[POS_ShpDate] <= _selMonth,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    ),
			    -- 總計列
			    CALCULATE (
			        [TTLQty],
			        TREATAS ( _custChanAllRFM, 'fact_clean'[CustomerNK], 'fact_clean'[DistName] ),
			        'fact_clean'[POS_ShpDate] >= _start,
			        'fact_clean'[POS_ShpDate] <= _selMonth,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			)
		formatString: 0
		lineageTag: 7d4e134f-d29f-4dfc-8619-38217cf39639

	measure PL_OrderCount12M =
			
			CALCULATE (
			    DISTINCTCOUNT ( fact_clean[POS_ShpDate] ),
			    DATESINPERIOD (
			        DIM_MONTH[MonthEnd],
			        MAX ( DIM_MONTH[MonthEnd] ),
			        -12,
			        MONTH
			    )
			)
		formatString: 0
		lineageTag: 22fcf5a6-3363-41c0-8168-18a743ae0130

	measure Is_PL_Repurchase =
			
			IF ( [PL_OrderCount12M] >= 2, 1, 0 )
		formatString: 0
		lineageTag: ff6b4983-79f6-4260-8702-a593e143f6c1

	measure PL_Customers_12M =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _start =
			    EDATE ( _selMonth, -11 )
			RETURN
			CALCULATE (
			    DISTINCTCOUNT ( fact_clean[CustomerNK] ),
			    fact_clean[POS_ShpDate] >= _start,
			    fact_clean[POS_ShpDate] <= _selMonth,
			    fact_clean[ResExt] > 0,
			    REMOVEFILTERS ( 'DIM_MONTH' )
			    -- 不要移除 ProductLine / DistName 等，
			    -- 讓 visual / slicer 指到 UARP 時，自然只算 UARP 的客戶
			)
		formatString: 0
		lineageTag: db34924e-baa2-47bc-ba9b-b77d1230efc4

	measure PL_TrueRepurchaseCustomers_12M =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )          -- 目前選到的 MonthEnd
			VAR _start =
			    EDATE ( _selMonth, -11 )              -- 往前 11 個月 = 12M 視窗起點
			
			-- 這 12M 內，所有有買到「目前產品線/產品、目前地區/渠道」的客戶清單
			VAR _AllCust =
			    CALCULATETABLE (
			        VALUES ( fact_clean[CustomerNK] ),
			        fact_clean[POS_ShpDate] >= _start,
			        fact_clean[POS_ShpDate] <= _selMonth,
			        fact_clean[ResExt] > 0,
			        -- 不吃 Month slicer，只用 _start ~ _selMonth 這個視窗
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			COUNTROWS (
			    FILTER (
			        _AllCust,
			        -- 對「這一位客戶」，在 12M 內買到目前產品線/產品的「不同月份數」
			        CALCULATE (
			            DISTINCTCOUNT ( fact_clean[MonthKey] ),
			            fact_clean[POS_ShpDate] >= _start,
			            fact_clean[POS_ShpDate] <= _selMonth,
			            fact_clean[ResExt] > 0,
			            REMOVEFILTERS ( 'DIM_MONTH' )
			        ) >= 2
			    )
			)
		formatString: 0
		lineageTag: 685d5f77-47e9-4c57-a7b3-265fa1449fd8

	measure PL_RepurchaseRate_12M =
			
			DIVIDE (
			    [PL_TrueRepurchaseCustomers_12M],
			    [PL_Customers_12M]
			)
		lineageTag: 9bd1eebf-2e43-45d4-b776-b4a7e494ee46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PL_TrueRepurchaseRate_12M =
			
			DIVIDE (
			    [PL_TrueRepurchaseCustomers_12M],   -- 分子：12M 內，在這條 ProductLine 上有 >=2 個月份出貨的客戶數
			    [PL_Customers_12M]              -- 分母：12M 內，有買這條 ProductLine 的全部客戶數
			)
		lineageTag: e73f7968-3e5c-4d70-a44e-66c928eb7570

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling12M_Retention =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )              -- 報表目前選到的 MonthEnd，例：2025/10/31
			VAR _currStart =
			    EDATE ( _selMonth, -11 )                   -- 當期 12M 的起始日（含）
			                                             -- 視窗 = _currStart ~ _selMonth
			
			-- 前一個 12M 視窗的結束與開始
			VAR _prevEnd =
			    EOMONTH ( _currStart, -1 )                 -- 當期視窗的前一個月月底
			VAR _prevStart =
			    EDATE ( _prevEnd, -11 )                    -- 往前推 11 個月 → 前期 12M 起始日
			                                             -- 視窗 = _prevStart ~ _prevEnd
			
			-- ❶ 前一期 12M 的「基底客戶」（有交易金額者）
			VAR _PrevCust =
			    CALCULATETABLE (
			        VALUES ( fact_clean[CustomerNK] ),      -- 去重後客戶清單
			        fact_clean[POS_ShpDate] >= _prevStart,
			        fact_clean[POS_ShpDate] <= _prevEnd,
			        fact_clean[ResExt] > 0,                 -- 只算有金額的出貨
			        REMOVEFILTERS ( 'DIM_MONTH' )           -- 日期用我們自己定義的兩個視窗
			        -- ⚠ 不移除其他 slicer → ProductLine、Channel、Geo 等都會被保留
			    )
			
			-- ❷ 當期 12M 的「有回來買的客戶」
			VAR _CurrCust =
			    CALCULATETABLE (
			        VALUES ( fact_clean[CustomerNK] ),
			        fact_clean[POS_ShpDate] >= _currStart,
			        fact_clean[POS_ShpDate] <= _selMonth,
			        fact_clean[ResExt] > 0,
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			
			-- ❸ 前期 12M 的客戶數（分母）
			VAR _PrevCnt =
			    COUNTROWS ( _PrevCust )
			
			-- ❹ 同時出現在兩個視窗的客戶數（分子 = Retained）
			VAR _RetainedCnt =
			    COUNTROWS ( INTERSECT ( _PrevCust, _CurrCust ) )
			
			RETURN
			    DIVIDE ( _RetainedCnt, _PrevCnt )
		lineageTag: 5e33e1c9-38a8-4c85-b11e-8e74c8642c23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PrevYearCustomers =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _startPrevYear =
			    EDATE ( _selMonth, -23 )   -- 從去年同月往前 11 個月
			VAR _endPrevYear =
			    EDATE ( _selMonth, -12 )   -- 去年該月
			
			RETURN
			CALCULATETABLE (
			    VALUES ( fact_clean[CustomerNK] ),
			    fact_clean[POS_ShpDate] >= _startPrevYear,
			    fact_clean[POS_ShpDate] <= _endPrevYear,
			    fact_clean[ResExt] > 0,
			    REMOVEFILTERS ( 'DIM_MONTH' )
			)
		lineageTag: 9a4cd220-7c41-475f-820f-140e4906fb18

	measure RetainedRevenue_12M =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			
			-- 今年視窗（選取 MonthEnd 往前 11 個月）
			VAR _startThisYear =
			    EDATE ( _selMonth, -11 )
			
			-- 去年對應視窗（比今年早 12 個月）
			VAR _startPrevYear =
			    EDATE ( _selMonth, -23 )
			VAR _endPrevYear =
			    EDATE ( _selMonth, -12 )
			
			-- 去年有買「目前篩選下同一產品（AdjPtNo）」的客戶清單
			VAR _PrevCustomers =
			    CALCULATETABLE (
			        VALUES ( fact_clean[CustomerNK] ),
			        fact_clean[POS_ShpDate] >= _startPrevYear,
			        fact_clean[POS_ShpDate] <= _endPrevYear,
			        fact_clean[ResExt] > 0,
			        -- 只移除 Month，用目前的 ProductLine / AdjPtNo / 地區 / 通路 篩選
			        REMOVEFILTERS ( 'DIM_MONTH' )
			    )
			RETURN
			-- 今年、同一產品、同一批客戶的營收（= Retained Revenue）
			CALCULATE (
			    SUM ( fact_clean[ResExt] ),
			    fact_clean[POS_ShpDate] >= _startThisYear,
			    fact_clean[POS_ShpDate] <= _selMonth,
			    fact_clean[ResExt] > 0,
			    TREATAS ( _PrevCustomers, fact_clean[CustomerNK] ),
			    REMOVEFILTERS ( 'DIM_MONTH' )
			)
		lineageTag: a6911053-40a2-406d-9564-e160982c96d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRevenue_12M =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _start =
			    EDATE ( _selMonth, -11 )
			RETURN
			CALCULATE (
			    SUM ( fact_clean[ResExt] ),
			    fact_clean[POS_ShpDate] >= _start,
			    fact_clean[POS_ShpDate] <= _selMonth,
			    fact_clean[ResExt] > 0,
			    REMOVEFILTERS ( 'DIM_MONTH' )
			)
		lineageTag: 894b0267-65a7-4ba8-b3e5-3073d5d5cdef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RetainedRevenuePct_12M =
			
			DIVIDE ( [RetainedRevenue_12M], [TotalRevenue_12M] )
		lineageTag: 0d5cd664-a3ae-4759-83b1-26919898dd15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Product_MonthsWithSales_12M =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			
			VAR _startMonth =
			    EDATE ( _selMonth, -11 )   -- 往前 11 個月，含當月共 12M
			
			-- 12M 內，該產品實際有出貨的月份清單
			VAR _MonthsTable =
			    SUMMARIZE (
			        CALCULATETABLE (
			            fact_clean,
			            fact_clean[POS_ShpDate] >= _startMonth,
			            fact_clean[POS_ShpDate] <= _selMonth,
			            fact_clean[ResExt] > 0,
			            REMOVEFILTERS ( 'DIM_MONTH' )   -- 不吃 Month slicer
			        ),
			        fact_clean[MonthKey]               -- 或用 EOMONTH(fact_clean[POS_ShpDate],0)
			    )
			RETURN
			    COUNTROWS ( _MonthsTable )
		formatString: 0
		lineageTag: 4b5d25d9-0a34-45d8-b3f6-4ebc29655069

	measure RepurchaseRevenue_12M =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _start =
			    EDATE ( _selMonth, -11 )         -- 最近 12M 視窗起點
			
			-- 1) 先取出 12M 內的明細，保留目前的產品 / 地區 / 渠道 篩選
			VAR _Base12M =
			    CALCULATETABLE (
			        fact_clean,
			        fact_clean[POS_ShpDate] >= _start,
			        fact_clean[POS_ShpDate] <= _selMonth,
			        fact_clean[ResExt] > 0,
			        REMOVEFILTERS ( 'DIM_MONTH' )  -- 只拿掉 Month slicer
			    )
			
			-- 2) 以「客戶」為粒度，計算這 12M 內有幾個不同的出貨月份
			VAR _CustAgg =
			    SUMMARIZE (
			        _Base12M,
			        fact_clean[CustomerNK],
			        "MonthCount", DISTINCTCOUNT ( fact_clean[MonthKey] )
			    )
			
			-- 3) MonthCount >= 2 的就是「真實跨月回購客」
			VAR _RepCust =
			    FILTER ( _CustAgg, [MonthCount] >= 2 )
			
			-- 4) 抽出這批回購客的 CustomerNK 清單
			VAR _RepCustList =
			    SELECTCOLUMNS ( _RepCust, "CustomerNK", [CustomerNK] )
			
			-- 5) 在同一個 12M 視窗內、同一個產品 / 產品線，計算這批回購客的營收
			RETURN
			CALCULATE (
			    SUM ( fact_clean[ResExt] ),
			    fact_clean[POS_ShpDate] >= _start,
			    fact_clean[POS_ShpDate] <= _selMonth,
			    fact_clean[ResExt] > 0,
			    TREATAS ( _RepCustList, fact_clean[CustomerNK] ),
			    REMOVEFILTERS ( 'DIM_MONTH' )   -- 一樣只拿掉 Month slicer
			)
		lineageTag: f33ca00f-56d8-4e12-8c46-491f7797fc28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RepurchaseRevenuePct_12M =
			
			DIVIDE (
			    [RepurchaseRevenue_12M],   -- 分子：今年 12M 回購客營收
			    [RFM Sales TY 12M]         -- 分母：今年 12M 總營收（你原本的 measure）
			)
		lineageTag: 311a52e0-041d-4397-b72a-9f5175aa8979

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '0  MEASURES' = m
		mode: import
		source =
				let
				    來源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"資料行 1" = _t]),
				    已變更類型 = Table.TransformColumnTypes(來源,{{"資料行 1", type text}}),
				    已移除資料行 = Table.RemoveColumns(已變更類型,{"資料行 1"})
				in
				    已移除資料行

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

