table cohort_retention_abc
	lineageTag: 299a81c5-bf65-43df-9088-493abfb678b0

	measure 'Retention %' =
			
			DIVIDE ( SUM ( cohort_retention_abc[ActiveCount] ),
			         SUM ( cohort_retention_abc[NewCount] ) )
		lineageTag: 2c998500-2856-4106-a441-e3ba121972b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Churn %' =
			
			1 - [Retention %]
		lineageTag: 35869afc-370c-434f-b6ca-8fc9573b42d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CohortMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4c3655d-2706-4d9d-bbaf-f3ec5ea708dc
		summarizeBy: none
		sourceColumn: CohortMonth

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthsSinceFirst
		dataType: int64
		formatString: 0
		lineageTag: 9b2bc17b-243d-46b0-9ae7-3103de46d1da
		summarizeBy: sum
		sourceColumn: MonthsSinceFirst

		annotation SummarizationSetBy = Automatic

	column GeoGroup
		dataType: string
		lineageTag: 948124d3-f4de-4139-933b-6847dc494398
		summarizeBy: none
		sourceColumn: GeoGroup

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: ac8e9189-e9b5-47e4-80bc-7836e953bf6d
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column FirstTier
		dataType: string
		lineageTag: 90773ac0-9aa4-41aa-b4d0-4b8fc5c1215b
		summarizeBy: none
		sourceColumn: FirstTier

		annotation SummarizationSetBy = Automatic

	column ActiveCount
		dataType: int64
		formatString: 0
		lineageTag: 25a177e7-3caf-4daf-9912-6c917e705faa
		summarizeBy: sum
		sourceColumn: ActiveCount

		annotation SummarizationSetBy = Automatic

	column NewCount
		dataType: int64
		formatString: 0
		lineageTag: d1ffdbd3-cd80-4021-bf9c-f7f8e8c82d5b
		summarizeBy: sum
		sourceColumn: NewCount

		annotation SummarizationSetBy = Automatic

	column RetentionPct
		dataType: double
		lineageTag: b1cd555f-8f50-46d9-b34d-fb6dcaad9535
		summarizeBy: sum
		sourceColumn: RetentionPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column m
		dataType: int64
		formatString: 0
		lineageTag: 0913aa45-6a9f-4487-8efb-86de931a3141
		summarizeBy: sum
		sourceColumn: m

		annotation SummarizationSetBy = Automatic

	column CohortYearMonth
		dataType: string
		lineageTag: 6c0d1f20-77cb-4d99-a4b2-2fd78a22bd78
		summarizeBy: none
		sourceColumn: CohortYearMonth

		annotation SummarizationSetBy = Automatic

	partition cohort_retention_abc = m
		mode: import
		source =
				let
				    來源 = Parquet.Document(File.Contents("C:\Users\rich\OneDrive\工作\Advantech\eCCP\duckDB\cohort_retention_abc.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    來源

	annotation PBI_ResultType = Table

