table CustomerChannelMap
	lineageTag: 601e7b6a-d89f-4f8f-8f81-b95b550bd264

	column CustomerNK
		dataType: string
		lineageTag: c3ee3168-4e6c-4ac3-9772-1e01ba7c4b81
		summarizeBy: none
		sourceColumn: CustomerNK

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: ff37a777-4586-4940-9c4a-053eefd82ba8
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	partition CustomerChannelMap = m
		mode: import
		source =
				// 在 Power Query 新增一個查詢：CustomerChannelMap
				let
				    Source      = fact_clean,
				    KeepCols    = Table.SelectColumns(Source, {"CustomerNK", "DistName"}),
				    Clean       = Table.TransformColumns(KeepCols, {
				                    {"CustomerNK", each Text.Trim(_), type text},
				                    {"DistName",   each Text.Trim(_), type text}
				                  }),
				    // 萬一有髒數據：同一客戶多通路，下面這段會幫你抓出來
				    CheckDup    = Table.Group(Clean, {"CustomerNK"},
				                    {{"Channels", each List.Distinct([DistName]), type list},
				                     {"Cnt", each List.Count(List.Distinct([DistName])), Int64.Type}}),
				    // 有問題的客戶（>1）你可以另外檢視
				    Suspects    = Table.SelectRows(CheckDup, each [Cnt] > 1),
				    // 正常情況：Cnt = 1，展開成一對一
				    ValidOnly   = Table.SelectRows(CheckDup, each [Cnt] = 1),
				    Expanded    = Table.ExpandListColumn(ValidOnly, "Channels"),
				    Renamed     = Table.RenameColumns(Expanded, {{"Channels", "Channel"}}),
				    Result      = Table.SelectColumns(Renamed, {"CustomerNK", "Channel"})
				in
				    Result

	annotation PBI_NavigationStepName = 導覽

	annotation PBI_ResultType = Table

