table DIM_REGION
	lineageTag: 2b1b196a-d927-4f16-bba1-7d0bac0bb5f7

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: 427d5e0b-6f35-462d-b029-0b7ed77efe61
		summarizeBy: count
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column GeoGroup
		dataType: string
		lineageTag: 92c6d245-2625-48a4-bd9f-bdb5dd69f21c
		summarizeBy: none
		sourceColumn: GeoGroup

		annotation SummarizationSetBy = Automatic

	partition DIM_REGION = m
		mode: import
		source =
				let
				    // 改成你的來源查詢名稱（例如 fact_clean 或 v_fact_clean）
				    Source = fact_clean,
				
				    // 取得所有欄位名
				    Cols = Table.ColumnNames(Source),
				
				    // 自動偵測可用的地區欄位
				    GeoCol =
				        if List.Contains(Cols, "GeoGroup") then "GeoGroup"
				        else if List.Contains(Cols, "ChannelGeoGroup") then "ChannelGeoGroup"
				        else if List.Contains(Cols, "Channel GeoGroup") then "Channel GeoGroup"
				        else if List.Contains(Cols, "Region") then "Region"
				        else null,
				
				    // 若找不到，就先新增一個 GeoGroup = "UNKNOWN"
				    EnsureGeo =
				        if GeoCol = null then
				            Table.AddColumn(Source, "GeoGroup", each "UNKNOWN", type text)
				        else
				            Source,
				
				    // 只取地區欄並統一命名為 GeoGroup
				    GeoOnly =
				        if GeoCol = null then
				            Table.SelectColumns(EnsureGeo, {"GeoGroup"})
				        else
				            Table.RenameColumns(
				                Table.SelectColumns(EnsureGeo, {GeoCol}),
				                {{GeoCol, "GeoGroup"}}
				            ),
				
				    // 去重
				    DistinctGeo = Table.Distinct(GeoOnly),
				
				    // 移除空值或空字串
				    RemoveNull = Table.SelectRows(DistinctGeo, each [GeoGroup] <> null and Text.Trim([GeoGroup]) <> "" and [GeoGroup] <> "UNKNOWN"),
				
				    // 加流水號做排序鍵（可選）
				    AddIndex = Table.AddIndexColumn(RemoveNull, "RegionID", 1, 1, Int64.Type),
				
				    // 排序欄位順序
				    Reorder = Table.ReorderColumns(AddIndex, {"RegionID", "GeoGroup"})
				in
				    Reorder

	annotation PBI_NavigationStepName = 導覽

	annotation PBI_ResultType = Table

