table FACT_SALES_MONTH
	lineageTag: 71034bea-a46c-47a8-9a8d-51fd69bd2e47

	measure 'Customers 24M' =
			
			VAR EndMonth   = MAX('dim_month'[MonthEnd])
			VAR StartMonth = EDATE(EndMonth, -24)
			RETURN
			CALCULATE(
			    DISTINCTCOUNT( FACT_SALES_MONTH[CustomerNK] ),
			    REMOVEFILTERS('dim_month'[MonthEnd]),
			    KEEPFILTERS( DATESBETWEEN('dim_month'[MonthEnd], StartMonth, EndMonth) )
			)
		formatString: 0
		lineageTag: 96a4242d-9897-4ed1-be40-167c20b37af8

	measure 'Customer Share in 24M' =
			
			VAR result = DIVIDE( [Customers 24M], [Customers 24M (All PDL)] )
			RETURN
			IF( NOT ISINSCOPE( FACT_SALES_MONTH[ProductLine] ), BLANK(), result )
		lineageTag: 1416d96d-93e5-4d10-8799-70387f566ebd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customers 24M (All PDL)' =
			
			VAR EndMonth   = MAX('dim_month'[MonthEnd])
			VAR StartMonth = EDATE(EndMonth, -24)
			RETURN
			CALCULATE(
			    DISTINCTCOUNT( FACT_SALES_MONTH[CustomerNK] ),
			    REMOVEFILTERS('dim_month'[MonthEnd]),
			    KEEPFILTERS( DATESBETWEEN('dim_month'[MonthEnd], StartMonth, EndMonth) ),
			    -- 關鍵：移除 PDL 的篩選，只保留其他篩選(區域、通路、Segment…)
			    REMOVEFILTERS( FACT_SALES_MONTH[ProductLine] )
			    -- 若你的 PDL 來自維表，另外加一行：
			    -- REMOVEFILTERS( 'DIM_PRODUCT'[ProductLine] )
			)
		formatString: 0
		lineageTag: ab4ff3c2-f31f-4613-a9ff-b3ad70dc9fba

	column CustomerNK
		dataType: string
		lineageTag: 7bd3a022-7c7b-4ce0-a401-fd3840377870
		summarizeBy: none
		sourceColumn: CustomerNK

		annotation SummarizationSetBy = Automatic

	column CustName
		dataType: string
		lineageTag: 9b1bc83c-3427-49e8-9a3f-2172709a6112
		summarizeBy: none
		sourceColumn: CustName

		annotation SummarizationSetBy = Automatic

	column CustCty
		dataType: string
		lineageTag: bf66c407-ac1e-42ee-82a8-89bce19836ca
		summarizeBy: none
		sourceColumn: CustCty

		annotation SummarizationSetBy = Automatic

	column CustZIP
		dataType: string
		lineageTag: 41f3264c-bbf5-40dc-a61d-632552e8f918
		summarizeBy: none
		sourceColumn: CustZIP

		annotation SummarizationSetBy = Automatic

	column CustSt
		dataType: string
		lineageTag: 62ccf68a-35e1-4cfd-ad6b-72b778e00dea
		summarizeBy: none
		sourceColumn: CustSt

		annotation SummarizationSetBy = Automatic

	column ChannelDistrict
		dataType: string
		lineageTag: 21677a8d-3d8f-4819-96bd-dbf29d00e21f
		summarizeBy: none
		sourceColumn: ChannelDistrict

		annotation SummarizationSetBy = Automatic

	column GeoGroup
		dataType: string
		lineageTag: c612d7f9-bd74-4938-9c31-dde79d48010c
		summarizeBy: none
		sourceColumn: GeoGroup

		annotation SummarizationSetBy = Automatic

	column DistType
		dataType: string
		lineageTag: 349f693d-4620-48e8-b651-02e46b8d6292
		summarizeBy: none
		sourceColumn: DistType

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: f097e72a-1d63-44f2-96b1-0e9ecda04ebf
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column ProductDivision
		dataType: string
		lineageTag: 64079e56-cc2c-44fb-87a4-8702cdfdf2eb
		summarizeBy: none
		sourceColumn: ProductDivision

		annotation SummarizationSetBy = Automatic

	column ProductGroup
		dataType: string
		lineageTag: d172f43f-cba0-43d8-ab9c-5e4a54a85024
		summarizeBy: none
		sourceColumn: ProductGroup

		annotation SummarizationSetBy = Automatic

	column ProductGroupRoll
		dataType: string
		lineageTag: 360bf245-ada4-48ab-b3d0-7de772aea211
		summarizeBy: none
		sourceColumn: ProductGroupRoll

		annotation SummarizationSetBy = Automatic

	column POS_ShpDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d5095a3-2fbf-421c-a84b-818fdbd9c478
		summarizeBy: none
		sourceColumn: POS_ShpDate

		annotation SummarizationSetBy = Automatic

	column PtNo
		dataType: string
		lineageTag: b970d758-c8e9-487f-96f7-d7b183770f85
		summarizeBy: none
		sourceColumn: PtNo

		annotation SummarizationSetBy = Automatic

	column AdjPtNo
		dataType: string
		lineageTag: 510bc6a5-b77a-4cb3-94b5-572d8906f0b0
		summarizeBy: none
		sourceColumn: AdjPtNo

		annotation SummarizationSetBy = Automatic

	column DistName
		dataType: string
		lineageTag: a1c052d4-40ad-400c-977d-0618eb520164
		summarizeBy: none
		sourceColumn: DistName

		annotation SummarizationSetBy = Automatic

	column CstExt
		dataType: double
		lineageTag: e8da2e2f-d862-4d64-b7d3-0b154b79b3b9
		summarizeBy: sum
		sourceColumn: CstExt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Double_UnitCst
		dataType: double
		lineageTag: 106ec30b-32db-4638-bbd8-d7f195aa2d38
		summarizeBy: sum
		sourceColumn: Double_UnitCst

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Double_UnitResale
		dataType: double
		lineageTag: c99064af-2aba-43e4-89cf-999ec670456e
		summarizeBy: sum
		sourceColumn: Double_UnitResale

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ResExt
		dataType: double
		lineageTag: fddfeeab-7f90-4b97-b2ea-90d4c4fe09e2
		summarizeBy: sum
		sourceColumn: ResExt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Qty
		dataType: int64
		formatString: 0
		lineageTag: 3cce212f-9fe0-48e0-8ba0-d7599ec114e6
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column ProductNK
		dataType: string
		lineageTag: 44f8c6df-ba9c-4292-a516-c9107e46224f
		summarizeBy: none
		sourceColumn: ProductNK

		annotation SummarizationSetBy = Automatic

	column UnitPrice_EA
		dataType: double
		lineageTag: ac45b7aa-0db5-4e7b-a2a2-067557479d7f
		summarizeBy: sum
		sourceColumn: UnitPrice_EA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SnapshotMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: 7ede6b57-ccc5-4e8c-ac01-95cb913ecda7
		summarizeBy: none
		sourceColumn: SnapshotMonth

		annotation SummarizationSetBy = Automatic

	column OrderCount
		dataType: int64
		formatString: 0
		lineageTag: 2035b35c-e925-4f1a-b08b-b06b20306e53
		summarizeBy: sum
		sourceColumn: OrderCount

		annotation SummarizationSetBy = Automatic

	column MonthlySales
		dataType: double
		lineageTag: c64def4a-8ecf-4777-9994-90fe805610eb
		summarizeBy: sum
		sourceColumn: MonthlySales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthEnd
		dataType: dateTime
		formatString: General Date
		lineageTag: 2f092308-00e9-4b0e-a1d8-be63b829455f
		summarizeBy: none
		sourceColumn: MonthEnd

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: int64
		formatString: 0
		lineageTag: 2fbcd0c1-6b4c-48f9-8dc9-499b4a656fc1
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column PurchaseSegment
		dataType: string
		lineageTag: bccc52c1-15a1-41e6-baba-333e74cdef6c
		summarizeBy: none
		sourceColumn: PurchaseSegment

		annotation SummarizationSetBy = Automatic

	column CustomerSegment
		dataType: string
		lineageTag: 258456cc-a857-475e-9e8c-a9925dff935c
		summarizeBy: none
		sourceColumn: CustomerSegment

		annotation SummarizationSetBy = Automatic

	column IsNew
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7968a73a-2861-442c-bba1-374ab3602389
		summarizeBy: none
		sourceColumn: IsNew

		annotation SummarizationSetBy = Automatic

	column FirstPurchaseMonth
		dataType: dateTime
		formatString: General Date
		lineageTag: f054b777-5f77-4094-bc9a-b98488f35265
		summarizeBy: none
		sourceColumn: FirstPurchaseMonth

		annotation SummarizationSetBy = Automatic

	column __Country_inferred
		dataType: string
		lineageTag: 30b3a344-5b12-4c24-ac03-bbdf48071725
		summarizeBy: none
		sourceColumn: __Country_inferred

		annotation SummarizationSetBy = Automatic

	column __ISO2_inferred
		dataType: string
		lineageTag: 86b1dea5-64c4-42fe-b390-3d791ad65890
		summarizeBy: none
		sourceColumn: __ISO2_inferred

		annotation SummarizationSetBy = Automatic

	column __Region_inferred
		dataType: string
		lineageTag: 7097bcbd-bea1-41d1-8fe4-9de386fc9d61
		summarizeBy: none
		sourceColumn: __Region_inferred

		annotation SummarizationSetBy = Automatic

	column CustDistKey
		dataType: string
		lineageTag: 6ec53cdb-a6fd-441c-93ce-056d6abb59c9
		summarizeBy: none
		sourceColumn: CustDistKey

		annotation SummarizationSetBy = Automatic

	column CustDistKeyMonth
		dataType: string
		lineageTag: 2cc77462-0a2d-49f0-b744-fb99787f2913
		summarizeBy: none
		sourceColumn: CustDistKeyMonth

		annotation SummarizationSetBy = Automatic

	partition FACT_SALES_MONTH = m
		mode: import
		source =
				let
				    來源 = Parquet.Document(File.Contents("C:\Users\rich\OneDrive\工作\Advantech\eCCP\duckDB\fact_clean_monthed.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    來源

	changedProperty = Name

	annotation PBI_ResultType = Table

