table month_map
	lineageTag: 65725826-d2ed-44e0-957b-fa492902e695

	measure StartMonthKey =
			
			VAR sIdx =
			    SELECTEDVALUE ( 'RollingStart'[Idx], 1 )  -- 沒選就當 1（Current-1）
			VAR maxRank =
			    CALCULATE ( MAX ( 'month_map'[MonthRank] ), ALL ( 'month_map' ) )
			VAR sRank = maxRank - sIdx
			RETURN
			CALCULATE (
			    MAX ( 'month_map'[MonthKey] ),
			    FILTER ( ALL ( 'month_map' ), 'month_map'[MonthRank] = sRank )
			)
		formatString: 0
		lineageTag: 92f92a7b-1c93-492a-9dae-7faf602927b2

		changedProperty = IsHidden

	measure EndMonthKey =
			
			VAR eIdx =
			    SELECTEDVALUE ( 'RollingEnd'[Idx], 0 )    -- 沒選就當 0（Current）
			VAR maxRank =
			    CALCULATE ( MAX ( 'month_map'[MonthRank] ), ALL ( 'month_map' ) )
			VAR eRank = maxRank - eIdx
			RETURN
			CALCULATE (
			    MAX ( 'month_map'[MonthKey] ),
			    FILTER ( ALL ( 'month_map' ), 'month_map'[MonthRank] = eRank )
			)
		formatString: 0
		lineageTag: 9e483385-e756-4937-a506-306ba6f43565

	column MonthKey
		dataType: int64
		formatString: 0
		lineageTag: 882f7830-83c8-4b14-8c4f-4c0a3d6716fb
		summarizeBy: none
		sourceColumn: MonthKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PrevMonthKey
		dataType: double
		formatString: 0
		lineageTag: 7f37628e-e613-43e1-847e-fb5ff241c2ac
		summarizeBy: count
		sourceColumn: PrevMonthKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: string
		lineageTag: e83e5ac3-f154-4a23-87df-d6f836a84427
		summarizeBy: none
		sourceColumn: YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QuarterKey = INT(month_map[YearMonth] / 100) * 10 + ROUNDUP(MOD(month_map[YearMonth],100) / 3, 0)
		lineageTag: afd05c6d-bc55-4b61-bc30-acbdf364dc73
		summarizeBy: count

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearQuarter =
			
			VAR Y = INT(month_map[YearMonth] / 100)
			VAR Q = ROUNDUP(MOD(month_map[YearMonth],100) / 3, 0)
			RETURN Y & " Q" & Q
		lineageTag: 6db997f1-3567-4758-a82e-f4dc40eb46b3
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthRank =
			
			VAR k = 'month_map'[MonthKey]
			RETURN
			    RANKX(
			        ALL('month_map'[MonthKey]),
			        'month_map'[MonthKey],
			        ,
			        ASC,
			        DENSE
			    )
		formatString: 0
		lineageTag: 690c421a-6dd2-4531-82b3-4975773946c6
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition month_map = m
		mode: import
		source =
				let
				    來源 = Parquet.Document(File.Contents("C:\Users\rich\OneDrive\工作\Advantech\eCCP\duckDB\month_map.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    來源

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

