table pareto_productgrouproll_geo_dist_productline_12m
	lineageTag: 4feb2354-9510-4a25-8bd0-7ebd1e97ffca

	measure CumPct_Pareto =
			
			MAX ( pareto_productgrouproll_geo_dist_productline_12m[CumPct] )
		lineageTag: c985e697-4881-48dd-a903-760e8b525b94

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalSales12M =
			
			VAR vMonth = MAX ( pareto_productgrouproll_geo_dist_productline_12m[MonthEnd] )
			VAR vGeo   = MAX ( pareto_productgrouproll_geo_dist_productline_12m[GeoGroup] )
			VAR vDist  = MAX ( pareto_productgrouproll_geo_dist_productline_12m[DistName] )
			VAR vPGR   = MAX ( pareto_productgrouproll_geo_dist_productline_12m[ProductGroupRoll] )
			RETURN
			CALCULATE (
			    SUM ( pareto_productgrouproll_geo_dist_productline_12m[Sales12M] ),
			    FILTER (
			        ALLSELECTED ( pareto_productgrouproll_geo_dist_productline_12m ),
			        pareto_productgrouproll_geo_dist_productline_12m[MonthEnd] = vMonth
			            && pareto_productgrouproll_geo_dist_productline_12m[GeoGroup] = vGeo
			            && pareto_productgrouproll_geo_dist_productline_12m[DistName] = vDist
			            && pareto_productgrouproll_geo_dist_productline_12m[ProductGroupRoll] = vPGR
			    )
			)
		lineageTag: 54e1f0db-4769-4421-bf18-f0d9a9156676

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CumSales12M =
			
			VAR vMonth = MAX ( pareto_productgrouproll_geo_dist_productline_12m[MonthEnd] )
			VAR vGeo   = MAX ( pareto_productgrouproll_geo_dist_productline_12m[GeoGroup] )
			VAR vDist  = MAX ( pareto_productgrouproll_geo_dist_productline_12m[DistName] )
			VAR vPGR   = MAX ( pareto_productgrouproll_geo_dist_productline_12m[ProductGroupRoll] )
			VAR vRank  = MAX ( pareto_productgrouproll_geo_dist_productline_12m[RankInMonth] )
			RETURN
			CALCULATE (
			    SUM ( pareto_productgrouproll_geo_dist_productline_12m[Sales12M] ),
			    FILTER (
			        ALLSELECTED ( pareto_productgrouproll_geo_dist_productline_12m ),
			        pareto_productgrouproll_geo_dist_productline_12m[MonthEnd] = vMonth
			            && pareto_productgrouproll_geo_dist_productline_12m[GeoGroup] = vGeo
			            && pareto_productgrouproll_geo_dist_productline_12m[DistName] = vDist
			            && pareto_productgrouproll_geo_dist_productline_12m[ProductGroupRoll] = vPGR
			            && pareto_productgrouproll_geo_dist_productline_12m[RankInMonth] <= vRank
			    )
			)
		lineageTag: 85c8cc16-c68a-4b1b-b1e4-b8e356781108

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CumPct %' =
			
			DIVIDE ( [CumSales12M], [TotalSales12M] )
		lineageTag: 8fc445dd-d806-4237-afbe-a506ace21721

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthEnd
		dataType: dateTime
		formatString: General Date
		lineageTag: 2d583ca7-0275-4452-8dfc-9be27e0f54ba
		summarizeBy: none
		sourceColumn: MonthEnd

		annotation SummarizationSetBy = Automatic

	column GeoGroup
		dataType: string
		lineageTag: 0cc471fb-9a3a-481b-aba1-3d014d2f80c9
		summarizeBy: none
		sourceColumn: GeoGroup

		annotation SummarizationSetBy = Automatic

	column DistName
		dataType: string
		lineageTag: fb1b57aa-b8f4-4099-a73c-2ed56f279931
		summarizeBy: none
		sourceColumn: DistName

		annotation SummarizationSetBy = Automatic

	column ProductGroupRoll
		dataType: string
		lineageTag: 52df3aea-c370-4ac7-b977-72e4548971c0
		summarizeBy: none
		sourceColumn: ProductGroupRoll

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 9bc6fe2b-33fa-4b19-a7e4-09901a3d6efc
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column Sales12M
		dataType: double
		lineageTag: fc80c6da-2d72-44b5-a9f2-1416789f25a5
		summarizeBy: sum
		sourceColumn: Sales12M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RankInMonth
		dataType: int64
		formatString: 0
		lineageTag: d6821ce9-910b-4983-ba66-13f7de423326
		summarizeBy: sum
		sourceColumn: RankInMonth

		annotation SummarizationSetBy = Automatic

	column CumSales
		dataType: double
		lineageTag: 1befb13f-a1b3-412f-b86a-25f14857f8cd
		summarizeBy: sum
		sourceColumn: CumSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalSales
		dataType: double
		lineageTag: a7d8019c-9b76-40c7-b589-d3ea5191cf63
		summarizeBy: sum
		sourceColumn: TotalSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CumPct
		dataType: double
		lineageTag: 8196426d-792c-4cdc-b896-1f0150ef1176
		summarizeBy: sum
		sourceColumn: CumPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition pareto_productgrouproll_geo_dist_productline_12m = m
		mode: import
		source =
				let
				    來源 = Parquet.Document(File.Contents("\\Mac\Home\Library\CloudStorage\OneDrive-個人\工作\Advantech\eCCP\duckDB\agg\pareto_productgrouproll_geo_dist_productline_12m.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    來源

	annotation PBI_ResultType = Table

