table pdl_month_agg
	lineageTag: ab018afa-0338-4497-bddf-215b8ad0b015

	measure 'Sales Slope 12M' =
			
			VAR _selMonth =
			    MAX ( 'DIM_MONTH'[MonthEnd] )
			VAR _months12 =
			    DATESINPERIOD ( 'DIM_MONTH'[MonthEnd], _selMonth, -11, MONTH )
			VAR _tbl =
			    ADDCOLUMNS (
			        _months12,
			        "x", RANKX ( _months12, [MonthEnd], , ASC ),
			        "y", CALCULATE ( SUM ( 'fact_clean'[ResExt] ) )
			    )
			VAR _line =
			    LINESTX ( _tbl, [y], [x] )
			RETURN
			    MAXX ( _line, [Slope1] )
		lineageTag: f171247a-f59b-4469-8777-bae7d711f891

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Slope 12M Z' =
			
			VAR _thisSlope = [Sales Slope 12M]
			VAR _selMonth  = MAX ( 'DIM_MONTH'[MonthEnd] )
			
			-- 同一個月、把所有產品線都拉進來算一遍斜率
			VAR _allSlopeThisMonth =
			    ADDCOLUMNS (
			        ALL ( 'fact_clean'[ProductLine] ),         -- 如果你的 ProductLine 是別張表，換成那張
			        "Slope12M",
			            CALCULATE (
			                [Sales Slope 12M],
			                KEEPFILTERS ( 'DIM_MONTH'[MonthEnd] = _selMonth )
			            )
			    )
			
			VAR _avgSlope =
			    AVERAGEX ( _allSlopeThisMonth, [Slope12M] )
			
			VAR _stdSlope =
			    STDEVX.P ( _allSlopeThisMonth, [Slope12M] )
			RETURN
			IF (
			    _stdSlope = 0 || ISBLANK ( _stdSlope ),
			    BLANK (),
			    ( _thisSlope - _avgSlope ) / _stdSlope
			)
		lineageTag: 9ba8fbeb-a8ca-4894-bdf7-abbaa083aa45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GeoGroup
		dataType: string
		lineageTag: 072eec0e-6013-46bc-9e08-5fcab9cfd939
		summarizeBy: none
		sourceColumn: GeoGroup

		annotation SummarizationSetBy = Automatic

	column DistName
		dataType: string
		lineageTag: 0bafbc65-2ab4-4d85-8469-e11a4846ea6a
		summarizeBy: none
		sourceColumn: DistName

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: abd7dbf2-9960-44fb-b791-0e07f8392d2e
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column MonthEnd
		dataType: dateTime
		formatString: General Date
		lineageTag: fe20abf3-59de-4c35-910d-a3f12802fcc6
		summarizeBy: none
		sourceColumn: MonthEnd

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 6f1dee8a-cd21-40d8-8939-e51736e429e3
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Slope12M
		dataType: double
		lineageTag: 9fa2d867-0c49-463b-a3de-29d1d284f275
		summarizeBy: sum
		sourceColumn: Slope12M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition pdl_month_agg = m
		mode: import
		source =
				let
				    來源 = Parquet.Document(File.Contents("C:\Users\rich\OneDrive\工作\Advantech\eCCP\duckDB\agg\pdl_month_agg.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    來源

	annotation PBI_ResultType = Table

