table Product_MonthlyTag
	lineageTag: 845f7e9b-7960-4d0d-9d84-f9ddc8025064

	measure '總銷售金額 M' = SUM ( 'Product_MonthlyTag'[SalesM] )
		lineageTag: 20989f17-7991-4eb2-b95a-c309305aec91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '總銷售數量 M' = SUM ( 'Product_MonthlyTag'[QtyM] )
		lineageTag: e555c01e-2ae5-49b1-8d8d-2e7b9f333db8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total SKUs' = ```
			
			    DISTINCTCOUNT ( 'Product_MonthlyTag'[ProductID] )
			```
		formatString: 0
		lineageTag: a3417b76-ce2a-41d3-8fbd-57f4a7eef7b0

	measure 'Active SKUs' = ```
			
			    CALCULATE (
			        DISTINCTCOUNT ( 'Product_MonthlyTag'[ProductID] ),
			        KEEPFILTERS ( 'Product_MonthlyTag'[Sales12M] > 0 )
			    )
			```
		formatString: 0
		lineageTag: 3d75a68c-3d41-418d-8ee2-0b3dfba0d9b1

	measure 'Top SKUs' = ```
			
			    CALCULATE ( DISTINCTCOUNT ( 'Product_MonthlyTag'[ProductID] ),
			                KEEPFILTERS ( 'Product_MonthlyTag'[TopMidTail] = "Top" ) )
			```
		formatString: 0
		lineageTag: 351e0dc9-777c-429e-87c1-0022b450f8be

	measure 'Mid SKUs' = ```
			
			    CALCULATE ( DISTINCTCOUNT ( 'Product_MonthlyTag'[ProductID] ),
			                KEEPFILTERS ( 'Product_MonthlyTag'[TopMidTail] = "Mid" ) )
			```
		formatString: 0
		lineageTag: d6ac0c30-cb92-42b0-8794-07383365bd78

	measure 'Tail SKUs' = ```
			
			    CALCULATE ( DISTINCTCOUNT ( 'Product_MonthlyTag'[ProductID] ),
			                KEEPFILTERS ( 'Product_MonthlyTag'[TopMidTail] = "Tail" ) )
			```
		formatString: 0
		lineageTag: fefad9d3-e7c1-4821-a499-bf286e42a239

	measure 'Top 總營業額' =
			
			CALCULATE ( [總銷售金額 M], KEEPFILTERS ( 'Product_MonthlyTag'[TopMidTail] = "Top" ) )
		lineageTag: 389483c3-c13c-4d3f-b4bf-8b658b6495bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mid 總營業額' =
			
			CALCULATE ( [總銷售金額 M], KEEPFILTERS ( 'Product_MonthlyTag'[TopMidTail] = "Mid" ) )
		lineageTag: e054ad57-3922-44ca-b68b-866838879504

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tail 總營業額' =
			
			CALCULATE ( [總銷售金額 M], KEEPFILTERS ( 'Product_MonthlyTag'[TopMidTail] = "Tail" ) )
		lineageTag: cb7c4834-9e1e-4dbc-bad7-8d9e3e9f21e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SnapshotMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: ec790e9a-8bee-402e-968a-bdc4ccd2dbd4
		summarizeBy: none
		sourceColumn: SnapshotMonth

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProductID
		dataType: string
		lineageTag: 4729f4ad-3725-4b8c-bace-4d4d94ea30b0
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column SalesM
		dataType: double
		lineageTag: f3174441-5628-4dfc-ae83-a64b7c0a62fb
		summarizeBy: sum
		sourceColumn: SalesM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QtyM
		dataType: double
		lineageTag: cb2985e1-78d2-47ee-9bc3-478dc67d3813
		summarizeBy: sum
		sourceColumn: QtyM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales12M
		dataType: double
		lineageTag: 52f85aa3-b24f-49b6-9e62-d0c5824876e0
		summarizeBy: sum
		sourceColumn: Sales12M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Qty12M
		dataType: double
		lineageTag: 7270277e-d892-4cb3-8d3e-0e13a6969cb1
		summarizeBy: sum
		sourceColumn: Qty12M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AvgLast3
		dataType: double
		lineageTag: f860b062-f367-4ea0-99f9-cf1f969f90bf
		summarizeBy: sum
		sourceColumn: AvgLast3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AvgPrev3
		dataType: double
		lineageTag: 058bc5e2-4bbb-4eea-b50c-ce15ff68a017
		summarizeBy: sum
		sourceColumn: AvgPrev3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Std6
		dataType: double
		lineageTag: 7c5848e7-1d91-4205-a43e-c32918ee46f2
		summarizeBy: sum
		sourceColumn: Std6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Avg6
		dataType: double
		lineageTag: 499536ed-06aa-412f-a44f-7395399af21b
		summarizeBy: sum
		sourceColumn: Avg6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TopMidTail
		dataType: string
		lineageTag: f32fdfed-4cae-405f-b9b2-9b289fb1be1a
		summarizeBy: none
		sourceColumn: TopMidTail

		annotation SummarizationSetBy = Automatic

	column Lifecycle
		dataType: string
		lineageTag: 769704c4-91c8-4bc6-b944-69d8d7cdc089
		summarizeBy: none
		sourceColumn: Lifecycle

		annotation SummarizationSetBy = Automatic

	partition Product_MonthlyTag = m
		mode: import
		source =
				let
				    來源 = Parquet.Document(File.Contents("C:\Users\rich\OneDrive\工作\Advantech\eCCP\duckDB\out\Product_MonthlyTag.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    來源

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 導覽

