table sales_m_pdl
	lineageTag: ca8ca614-5db4-4d93-a6c2-b44e57907853

	measure TTLRevenue_12M =
			
			CALCULATE (
			    SUM ( sales_m_pdl[Sales] ),
			    DATESINPERIOD (
			        'DIM_MONTH'[MonthEnd],
			        MAX ( 'DIM_MONTH'[MonthEnd] ),
			        -12,
			        MONTH
			    )
			)
		lineageTag: 871497e3-eadb-4be2-8998-30aedcb88e72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Diff_Sales =
			
			VAR cur = CALCULATE (
			    SUM ( sales_m_pdl[Sales] ),
			    KEEPFILTERS ( DIM_MONTH[Rolling12M_Label] = "Current" )
			)
			VAR prev = CALCULATE (
			    SUM ( sales_m_pdl[Sales] ),
			    KEEPFILTERS ( DIM_MONTH[Rolling12M_Label] = "Current-1" )
			)
			RETURN cur - prev
		lineageTag: 6c923871-da57-464f-bdff-668871175610

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerNK
		dataType: string
		lineageTag: 55b1c14d-f49b-4d8d-8d3f-b076485bf6d8
		summarizeBy: none
		sourceColumn: CustomerNK

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: eb5fd232-929e-4d5e-86e2-7e343ddcc5a9
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: int64
		formatString: 0
		lineageTag: 060de573-afe0-4067-8313-f96100d65703
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 62d55efe-d542-4e91-882a-f02f5096bbe7
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CumSales
		dataType: double
		lineageTag: 230f1ad0-5eed-47b2-8336-fb408ae58827
		summarizeBy: sum
		sourceColumn: CumSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: fe1f1d7b-bc17-44d5-9773-efd1644b32ee
		summarizeBy: none
		sourceColumn: YearMonth

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GeoGroup
		dataType: string
		lineageTag: 6d980123-a20c-4f59-af1a-0cec8c25711b
		summarizeBy: none
		sourceColumn: GeoGroup

		annotation SummarizationSetBy = Automatic

	column MonthEnd
		dataType: dateTime
		formatString: General Date
		lineageTag: dfc2d6e8-598f-414b-b91d-de4e0667fbff
		summarizeBy: none
		sourceColumn: MonthEnd

		annotation SummarizationSetBy = Automatic

	column DistName
		dataType: string
		lineageTag: 61b14958-a9fb-4030-bffe-c6aefd2e53c8
		summarizeBy: none
		sourceColumn: DistName

		annotation SummarizationSetBy = Automatic

	column ProductGroupRoll
		dataType: string
		lineageTag: 121e7808-6169-4eae-8d0c-e05169035d59
		summarizeBy: none
		sourceColumn: ProductGroupRoll

		annotation SummarizationSetBy = Automatic

	column PDL_Key = ```
			
			    sales_m_pdl[CustomerNK] & "|" &
			    sales_m_pdl[DistName]   & "|" &
			    sales_m_pdl[GeoGroup]   & "|" &
			    FORMAT ( sales_m_pdl[MonthEnd], "yyyy-MM-dd" )
			```
		lineageTag: 76b48086-ac34-4501-9dae-4935cc05e396
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CustMonthKey = ```
			
			    sales_m_pdl[CustomerNK] & "|" &
			    sales_m_pdl[DistName]   & "|" &
			    sales_m_pdl[GeoGroup]   & "|" &
			    FORMAT ( sales_m_pdl[MonthEnd], "yyyyMM" )
			```
		lineageTag: 1d6a1d2c-ebae-4b3b-bc62-40aae10fe92d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition sales_m_pdl = m
		mode: import
		source =
				let
				    來源 = Parquet.Document(File.Contents("C:\Users\rich\OneDrive\工作\Advantech\eCCP\duckDB\sales_m_pdl.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    來源

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 導覽

