table Tier_To
	lineageTag: c9c334da-5a35-4300-a03c-cb59a8838a85

	measure 'Col % of Matrix' =
			
			VAR denom =
			    CALCULATE ( [Flow Customers (Boundary)], REMOVEFILTERS ( 'Tier_From' ) )
			RETURN
			    DIVIDE ( [Flow Customers (Boundary)], denom )
		lineageTag: a2b08ad1-2a98-4386-887f-87eae1c4a99f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tier to'
		lineageTag: 9493d875-afd0-4efe-8ec7-e4da1a2d63e8
		summarizeBy: none
		isNameInferred
		sourceColumn: [Tier to]
		sortByColumn: ToOrder

		annotation SummarizationSetBy = Automatic

	column ToOrder
		formatString: 0
		lineageTag: 02050ff0-866a-4fcb-b644-f8ae4e30d8fe
		summarizeBy: sum
		isNameInferred
		sourceColumn: [ToOrder]

		annotation SummarizationSetBy = Automatic

	partition Tier_To = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Tier to", STRING,
				    "ToOrder", INTEGER,
				    {
				        {"Head",     1},
				        {"Mid",      2},
				        {"Tail",     3},
				        {"NoSpend",  4}
				    }
				)

	annotation PBI_Id = c1ccd21eb9a3448e8633c59656b57775

