table WF_Cat
	lineageTag: 7931cf55-90b6-45d6-9ccf-af1db72f2fb2

	measure WF_GetSelections =
			
			VAR _SelTier     = SELECTEDVALUE ( TierPicker[Tier], "Tail" )
			VAR _StartQKey   = SELECTEDVALUE ( StartQuarter[QuarterKey] )
			VAR _EndQKey     = SELECTEDVALUE ( EndQuarter[QuarterKey] )
			RETURN
			    "Tier=" & _SelTier &
			    " / Start=" & COALESCE ( FORMAT ( _StartQKey, "0" ), "-" ) &
			    " / End=" & COALESCE ( FORMAT ( _EndQKey, "0" ), "-" )
		lineageTag: 8c028428-940f-4aa9-aa75-bf68a46db8e0

	measure Sales_Start_SelectedTier =
			
			VAR _tier = [SelTier]
			VAR _qKey = [StartQKey]
			VAR _custSet =
			    CALCULATETABLE (
			        VALUES ( Customer_Tier_Quarter[CustomerNK] ),
			        -- 先清掉時間，再用 QuarterKey 指定「起點季」
			        REMOVEFILTERS ( DIM_MONTH ),
			        Customer_Tier_Quarter[QuarterKey] = _qKey,
			        Customer_Tier_Quarter[Tier] = _tier
			    )
			RETURN
			IF (
			    ISBLANK ( _tier ) || ISBLANK ( _qKey ) || COUNTROWS ( _custSet ) = 0,
			    BLANK (),
			    CALCULATE (
			        SUM ( fact_clean[ResExt] ),
			        -- 把客戶名單套到 fact（不需關聯）
			        TREATAS ( _custSet, DIM_CUSTOMER[CustomerNK] ),
			        -- 再次保險：忽略外部所有時間篩選，明確指定這一季
			        REMOVEFILTERS ( DIM_MONTH ),
			        DIM_MONTH[QuarterKey] = _qKey
			    )
			)
		lineageTag: d970d816-f2d9-4961-8886-9baacc4ee430

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SelTier =
			
			SELECTEDVALUE ( TierPicker[Tier], "Tail" )
		lineageTag: 244dfa84-551c-41cc-9c20-a3176d462ba1

	measure StartQKey = ```
			
			VAR k = SELECTEDVALUE ( StartQuarter[QuarterKey] )
			RETURN IF ( ISBLANK(k), BLANK(), INT(k) )         -- 確保是整數
			
			```
		formatString: 0
		lineageTag: 1c9a755d-575f-4d43-907c-9ce5bba1f2a3

	measure EndQKey =
			
			VAR k = SELECTEDVALUE ( EndQuarter[QuarterKey] )
			RETURN IF ( ISBLANK(k), BLANK(), INT(k) )
		formatString: 0
		lineageTag: 8de94125-681d-47e7-bdaf-2c95ecf8427c

	measure Sales_End_SelectedTier =
			
			VAR _tier = [SelTier]
			VAR _qKey = [EndQKey]
			VAR _custSet =
			    CALCULATETABLE (
			        VALUES ( Customer_Tier_Quarter[CustomerNK] ),
			        REMOVEFILTERS ( DIM_MONTH ),
			        Customer_Tier_Quarter[QuarterKey] = _qKey,
			        Customer_Tier_Quarter[Tier] = _tier
			    )
			RETURN
			IF (
			    ISBLANK ( _tier ) || ISBLANK ( _qKey ) || COUNTROWS ( _custSet ) = 0,
			    BLANK (),
			    CALCULATE (
			        SUM ( fact_clean[ResExt] ),
			        TREATAS ( _custSet, DIM_CUSTOMER[CustomerNK] ),
			        REMOVEFILTERS ( DIM_MONTH ),
			        DIM_MONTH[QuarterKey] = _qKey
			    )
			)
		lineageTag: f6947e7e-078f-4018-aeb3-8f71f17a2293

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Delta_SelectedTier =
			
			VAR _start = [Sales_Start_SelectedTier]
			VAR _end   = [Sales_End_SelectedTier]
			RETURN
			IF ( OR ( ISBLANK ( _start ), ISBLANK ( _end ) ), BLANK (), _end - _start )
		lineageTag: 267d4855-e71f-4030-b242-86725c18768f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'StartFactRows (debug)' =
			
			VAR _q    = [StartQKey]
			VAR _tier = [SelTier]
			VAR _custSet =
			    CALCULATETABLE(
			        VALUES( Customer_Tier_Quarter[CustomerNK] ),
			        Customer_Tier_Quarter[QuarterKey] = _q,
			        Customer_Tier_Quarter[Tier]       = _tier
			    )
			RETURN
			IF(
			    OR( ISBLANK(_q), ISBLANK(_tier) ),
			    BLANK(),
			    CALCULATE(
			        COUNTROWS( fact_clean ),
			        REMOVEFILTERS( DIM_MONTH ),
			        TREATAS( {_q}, DIM_MONTH[QuarterKey] ),
			        TREATAS( _custSet, fact_clean[CustomerNK] )
			    )
			)
		lineageTag: 574e425a-2a27-4dfa-823d-4a0dcae57720

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '-- 該起點季／Tier 的客戶數（只查 Customer_Tier_Quarter）StartRows (debug)' =
			
			VAR _q    = [StartQKey]
			VAR _tier = [SelTier]
			VAR _custSet =
			    CALCULATETABLE (
			        VALUES ( Customer_Tier_Quarter[CustomerNK] ),
			        Customer_Tier_Quarter[QuarterKey] = _q,
			        Customer_Tier_Quarter[Tier]       = _tier
			    )
			RETURN
			    IF ( ISBLANK ( _q ) || ISBLANK ( _tier ), BLANK (), COUNTROWS ( _custSet ) )
		formatString: 0
		lineageTag: 38d3698b-b918-4d22-ac03-284e732e9308

	measure 'EndRows (debug)' =
			
			VAR _q    = [EndQKey]
			VAR _tier = [SelTier]
			VAR _custSet =
			    CALCULATETABLE(
			        VALUES( Customer_Tier_Quarter[CustomerNK] ),
			        Customer_Tier_Quarter[QuarterKey] = _q,
			        Customer_Tier_Quarter[Tier]       = _tier
			    )
			RETURN
			IF( OR( ISBLANK(_q), ISBLANK(_tier) ),
			    BLANK(),
			    COUNTROWS( _custSet )
			)
		formatString: 0
		lineageTag: 8e36518c-c6d3-45b4-a130-90b71e1d2d16

	measure 'StartRows (debug)' = ```
			
			VAR _q    = [StartQKey]
			VAR _tier = [SelTier]
			VAR _custSet =
			    CALCULATETABLE(
			        VALUES( Customer_Tier_Quarter[CustomerNK] ),
			        Customer_Tier_Quarter[QuarterKey] = _q,
			        Customer_Tier_Quarter[Tier]       = _tier
			    )
			RETURN
			IF( OR( ISBLANK(_q), ISBLANK(_tier) ),
			    BLANK(),
			    COUNTROWS( _custSet )
			)
			
			```
		lineageTag: 249709a2-33d8-4a65-bfcf-e3f63662c54b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EndSales_All =
			
			VAR _q    = [EndQKey]
			VAR _tier = [SelTier]
			VAR _custSet =
			    CALCULATETABLE (
			        VALUES ( Customer_Tier_Quarter[CustomerNK] ),
			        Customer_Tier_Quarter[QuarterKey] = _q,
			        Customer_Tier_Quarter[Tier]       = _tier
			    )
			RETURN
			IF (
			    ISBLANK ( _q ) || ISBLANK ( _tier ) || ISEMPTY ( _custSet ),
			    BLANK (),
			    CALCULATE (
			        COALESCE ( SUM ( fact_clean[ResExt] ), 0 ),
			        REMOVEFILTERS ( DIM_MONTH ),
			        KEEPFILTERS ( DIM_MONTH[QuarterKey] = _q ),
			        TREATAS ( _custSet, fact_clean[CustomerNK] )
			    )
			)
		lineageTag: 28ae47fd-6566-4281-ad04-9ed2792261c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure EndSet_Count =
			
			VAR _q    = [EndQKey]
			VAR _tier = [SelTier]
			RETURN
			IF (
			    ISBLANK ( _q ) || ISBLANK ( _tier ),
			    BLANK (),
			    COUNTROWS (
			        CALCULATETABLE (
			            VALUES ( Customer_Tier_Quarter[CustomerNK] ),
			            Customer_Tier_Quarter[QuarterKey] = _q,
			            Customer_Tier_Quarter[Tier]       = _tier
			        )
			    )
			)
		lineageTag: 89769874-ee94-4fb6-93aa-4b532104ef7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WF_Cat
		lineageTag: 4227840b-4a05-441d-a113-30f5a7bc5064
		summarizeBy: none
		isNameInferred
		sourceColumn: [WF_Cat]

		annotation SummarizationSetBy = Automatic

	column Sort
		formatString: 0
		lineageTag: 9445afff-85ca-4af4-92ec-56af169ada42
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Sort]

		annotation SummarizationSetBy = Automatic

	partition WF_Cat = calculated
		mode: import
		source =
				
				DATATABLE ( "WF_Cat", STRING, "Sort", INTEGER,
				  { { "Start", 1 }, { "End", 2 } }
				)

	annotation PBI_Id = e6b3349582754dd9ac08b487819e8d26

